export const cityData = [
  { label: "Kolhapur,Maharashtra", value: "Kolhapur,Maharashtra" },
  {
    label: "Port Blair,Andaman & Nicobar Islands",
    value: "Port Blair,Andaman & Nicobar Islands",
  },
  { label: "Adilabad,Andhra Pradesh", value: "Adilabad,Andhra Pradesh" },
  { label: "Adoni,Andhra Pradesh", value: "Adoni,Andhra Pradesh" },
  {
    label: "Amadalavalasa,Andhra Pradesh",
    value: "Amadalavalasa,Andhra Pradesh",
  },
  { label: "Amalapuram,Andhra Pradesh", value: "Amalapuram,Andhra Pradesh" },
  { label: "Anakapalle,Andhra Pradesh", value: "Anakapalle,Andhra Pradesh" },
  { label: "Anantapur,Andhra Pradesh", value: "Anantapur,Andhra Pradesh" },
  { label: "Badepalle,Andhra Pradesh", value: "Badepalle,Andhra Pradesh" },
  {
    label: "Banganapalle,Andhra Pradesh",
    value: "Banganapalle,Andhra Pradesh",
  },
  { label: "Bapatla,Andhra Pradesh", value: "Bapatla,Andhra Pradesh" },
  { label: "Bellampalle,Andhra Pradesh", value: "Bellampalle,Andhra Pradesh" },
  {
    label: "Bethamcherla,Andhra Pradesh",
    value: "Bethamcherla,Andhra Pradesh",
  },
  {
    label: "Bhadrachalam,Andhra Pradesh",
    value: "Bhadrachalam,Andhra Pradesh",
  },
  { label: "Bhainsa,Andhra Pradesh", value: "Bhainsa,Andhra Pradesh" },
  {
    label: "Bheemunipatnam,Andhra Pradesh",
    value: "Bheemunipatnam,Andhra Pradesh",
  },
  { label: "Bhimavaram,Andhra Pradesh", value: "Bhimavaram,Andhra Pradesh" },
  { label: "Bhongir,Andhra Pradesh", value: "Bhongir,Andhra Pradesh" },
  { label: "Bobbili,Andhra Pradesh", value: "Bobbili,Andhra Pradesh" },
  { label: "Bodhan,Andhra Pradesh", value: "Bodhan,Andhra Pradesh" },
  {
    label: "Chilakaluripet,Andhra Pradesh",
    value: "Chilakaluripet,Andhra Pradesh",
  },
  { label: "Chirala,Andhra Pradesh", value: "Chirala,Andhra Pradesh" },
  { label: "Chittoor,Andhra Pradesh", value: "Chittoor,Andhra Pradesh" },
  { label: "Cuddapah,Andhra Pradesh", value: "Cuddapah,Andhra Pradesh" },
  { label: "Devarakonda,Andhra Pradesh", value: "Devarakonda,Andhra Pradesh" },
  { label: "Dharmavaram,Andhra Pradesh", value: "Dharmavaram,Andhra Pradesh" },
  { label: "Eluru,Andhra Pradesh", value: "Eluru,Andhra Pradesh" },
  { label: "Farooqnagar,Andhra Pradesh", value: "Farooqnagar,Andhra Pradesh" },
  { label: "Gadwal,Andhra Pradesh", value: "Gadwal,Andhra Pradesh" },
  { label: "Gooty,Andhra Pradesh", value: "Gooty,Andhra Pradesh" },
  { label: "Gudivada,Andhra Pradesh", value: "Gudivada,Andhra Pradesh" },
  { label: "Gudur,Andhra Pradesh", value: "Gudur,Andhra Pradesh" },
  { label: "Guntakal,Andhra Pradesh", value: "Guntakal,Andhra Pradesh" },
  { label: "Guntur,Andhra Pradesh", value: "Guntur,Andhra Pradesh" },
  {
    label: "Hanuman Junction,Andhra Pradesh",
    value: "Hanuman Junction,Andhra Pradesh",
  },
  { label: "Hindupur,Andhra Pradesh", value: "Hindupur,Andhra Pradesh" },
  { label: "Hyderabad,Andhra Pradesh", value: "Hyderabad,Andhra Pradesh" },
  { label: "Ichchapuram,Andhra Pradesh", value: "Ichchapuram,Andhra Pradesh" },
  { label: "Jaggaiahpet,Andhra Pradesh", value: "Jaggaiahpet,Andhra Pradesh" },
  { label: "Jagtial,Andhra Pradesh", value: "Jagtial,Andhra Pradesh" },
  {
    label: "Jammalamadugu,Andhra Pradesh",
    value: "Jammalamadugu,Andhra Pradesh",
  },
  { label: "Jangaon,Andhra Pradesh", value: "Jangaon,Andhra Pradesh" },
  { label: "Kadapa,Andhra Pradesh", value: "Kadapa,Andhra Pradesh" },
  { label: "Kadiri,Andhra Pradesh", value: "Kadiri,Andhra Pradesh" },
  { label: "Kagaznagar,Andhra Pradesh", value: "Kagaznagar,Andhra Pradesh" },
  { label: "Kakinada,Andhra Pradesh", value: "Kakinada,Andhra Pradesh" },
  { label: "Kalyandurg,Andhra Pradesh", value: "Kalyandurg,Andhra Pradesh" },
  { label: "Kamareddy,Andhra Pradesh", value: "Kamareddy,Andhra Pradesh" },
  { label: "Kandukur,Andhra Pradesh", value: "Kandukur,Andhra Pradesh" },
  { label: "Karimnagar,Andhra Pradesh", value: "Karimnagar,Andhra Pradesh" },
  { label: "Kavali,Andhra Pradesh", value: "Kavali,Andhra Pradesh" },
  { label: "Khammam,Andhra Pradesh", value: "Khammam,Andhra Pradesh" },
  { label: "Koratla,Andhra Pradesh", value: "Koratla,Andhra Pradesh" },
  { label: "Kothagudem,Andhra Pradesh", value: "Kothagudem,Andhra Pradesh" },
  { label: "Kothapeta,Andhra Pradesh", value: "Kothapeta,Andhra Pradesh" },
  { label: "Kovvur,Andhra Pradesh", value: "Kovvur,Andhra Pradesh" },
  { label: "Kurnool,Andhra Pradesh", value: "Kurnool,Andhra Pradesh" },
  {
    label: "Kyathampalle,Andhra Pradesh",
    value: "Kyathampalle,Andhra Pradesh",
  },
  { label: "Macherla,Andhra Pradesh", value: "Macherla,Andhra Pradesh" },
  {
    label: "Machilipatnam,Andhra Pradesh",
    value: "Machilipatnam,Andhra Pradesh",
  },
  { label: "Madanapalle,Andhra Pradesh", value: "Madanapalle,Andhra Pradesh" },
  { label: "Mahbubnagar,Andhra Pradesh", value: "Mahbubnagar,Andhra Pradesh" },
  { label: "Mancherial,Andhra Pradesh", value: "Mancherial,Andhra Pradesh" },
  { label: "Mandamarri,Andhra Pradesh", value: "Mandamarri,Andhra Pradesh" },
  { label: "Mandapeta,Andhra Pradesh", value: "Mandapeta,Andhra Pradesh" },
  { label: "Manuguru,Andhra Pradesh", value: "Manuguru,Andhra Pradesh" },
  { label: "Markapur,Andhra Pradesh", value: "Markapur,Andhra Pradesh" },
  { label: "Medak,Andhra Pradesh", value: "Medak,Andhra Pradesh" },
  { label: "Miryalaguda,Andhra Pradesh", value: "Miryalaguda,Andhra Pradesh" },
  { label: "Mogalthur,Andhra Pradesh", value: "Mogalthur,Andhra Pradesh" },
  { label: "Nagari,Andhra Pradesh", value: "Nagari,Andhra Pradesh" },
  {
    label: "Nagarkurnool,Andhra Pradesh",
    value: "Nagarkurnool,Andhra Pradesh",
  },
  { label: "Nandyal,Andhra Pradesh", value: "Nandyal,Andhra Pradesh" },
  { label: "Narasapur,Andhra Pradesh", value: "Narasapur,Andhra Pradesh" },
  {
    label: "Narasaraopet,Andhra Pradesh",
    value: "Narasaraopet,Andhra Pradesh",
  },
  { label: "Narayanpet,Andhra Pradesh", value: "Narayanpet,Andhra Pradesh" },
  { label: "Narsipatnam,Andhra Pradesh", value: "Narsipatnam,Andhra Pradesh" },
  { label: "Nellore,Andhra Pradesh", value: "Nellore,Andhra Pradesh" },
  { label: "Nidadavole,Andhra Pradesh", value: "Nidadavole,Andhra Pradesh" },
  { label: "Nirmal,Andhra Pradesh", value: "Nirmal,Andhra Pradesh" },
  { label: "Nizamabad,Andhra Pradesh", value: "Nizamabad,Andhra Pradesh" },
  { label: "Nuzvid,Andhra Pradesh", value: "Nuzvid,Andhra Pradesh" },
  { label: "Ongole,Andhra Pradesh", value: "Ongole,Andhra Pradesh" },
  { label: "Palacole,Andhra Pradesh", value: "Palacole,Andhra Pradesh" },
  {
    label: "Palasa Kasibugga,Andhra Pradesh",
    value: "Palasa Kasibugga,Andhra Pradesh",
  },
  { label: "Palwancha,Andhra Pradesh", value: "Palwancha,Andhra Pradesh" },
  {
    label: "Parvathipuram,Andhra Pradesh",
    value: "Parvathipuram,Andhra Pradesh",
  },
  { label: "Pedana,Andhra Pradesh", value: "Pedana,Andhra Pradesh" },
  { label: "Peddapuram,Andhra Pradesh", value: "Peddapuram,Andhra Pradesh" },
  { label: "Pithapuram,Andhra Pradesh", value: "Pithapuram,Andhra Pradesh" },
  { label: "Pondur,Andhra pradesh", value: "Pondur,Andhra pradesh" },
  { label: "Ponnur,Andhra Pradesh", value: "Ponnur,Andhra Pradesh" },
  { label: "Proddatur,Andhra Pradesh", value: "Proddatur,Andhra Pradesh" },
  { label: "Punganur,Andhra Pradesh", value: "Punganur,Andhra Pradesh" },
  { label: "Puttur,Andhra Pradesh", value: "Puttur,Andhra Pradesh" },
  { label: "Rajahmundry,Andhra Pradesh", value: "Rajahmundry,Andhra Pradesh" },
  { label: "Rajam,Andhra Pradesh", value: "Rajam,Andhra Pradesh" },
  {
    label: "Ramachandrapuram,Andhra Pradesh",
    value: "Ramachandrapuram,Andhra Pradesh",
  },
  { label: "Ramagundam,Andhra Pradesh", value: "Ramagundam,Andhra Pradesh" },
  { label: "Rayachoti,Andhra Pradesh", value: "Rayachoti,Andhra Pradesh" },
  { label: "Rayadurg,Andhra Pradesh", value: "Rayadurg,Andhra Pradesh" },
  { label: "Renigunta,Andhra Pradesh", value: "Renigunta,Andhra Pradesh" },
  { label: "Repalle,Andhra Pradesh", value: "Repalle,Andhra Pradesh" },
  { label: "Sadasivpet,Andhra Pradesh", value: "Sadasivpet,Andhra Pradesh" },
  { label: "Salur,Andhra Pradesh", value: "Salur,Andhra Pradesh" },
  { label: "Samalkot,Andhra Pradesh", value: "Samalkot,Andhra Pradesh" },
  { label: "Sangareddy,Andhra Pradesh", value: "Sangareddy,Andhra Pradesh" },
  {
    label: "Sattenapalle,Andhra Pradesh",
    value: "Sattenapalle,Andhra Pradesh",
  },
  { label: "Siddipet,Andhra Pradesh", value: "Siddipet,Andhra Pradesh" },
  { label: "Singapur,Andhra Pradesh", value: "Singapur,Andhra Pradesh" },
  { label: "Sircilla,Andhra Pradesh", value: "Sircilla,Andhra Pradesh" },
  { label: "Srikakulam,Andhra Pradesh", value: "Srikakulam,Andhra Pradesh" },
  {
    label: "Srikalahasti,Andhra Pradesh",
    value: "Srikalahasti,Andhra Pradesh",
  },
  { label: "Suryapet,Andhra Pradesh", value: "Suryapet,Andhra Pradesh" },
  {
    label: "Tadepalligudem,Andhra Pradesh",
    value: "Tadepalligudem,Andhra Pradesh",
  },
  { label: "Tadpatri,Andhra Pradesh", value: "Tadpatri,Andhra Pradesh" },
  { label: "Tandur,Andhra Pradesh", value: "Tandur,Andhra Pradesh" },
  { label: "Tanuku,Andhra Pradesh", value: "Tanuku,Andhra Pradesh" },
  { label: "Tenali,Andhra Pradesh", value: "Tenali,Andhra Pradesh" },
  { label: "Tirupati,Andhra Pradesh", value: "Tirupati,Andhra Pradesh" },
  { label: "Tuni,Andhra Pradesh", value: "Tuni,Andhra Pradesh" },
  { label: "Uravakonda,Andhra Pradesh", value: "Uravakonda,Andhra Pradesh" },
  { label: "Venkatagiri,Andhra Pradesh", value: "Venkatagiri,Andhra Pradesh" },
  { label: "Vicarabad,Andhra Pradesh", value: "Vicarabad,Andhra Pradesh" },
  { label: "Vijayawada,Andhra Pradesh", value: "Vijayawada,Andhra Pradesh" },
  { label: "Vinukonda,Andhra Pradesh", value: "Vinukonda,Andhra Pradesh" },
  {
    label: "Visakhapatnam,Andhra Pradesh",
    value: "Visakhapatnam,Andhra Pradesh",
  },
  {
    label: "Vizianagaram,Andhra Pradesh",
    value: "Vizianagaram,Andhra Pradesh",
  },
  { label: "Wanaparthy,Andhra Pradesh", value: "Wanaparthy,Andhra Pradesh" },
  { label: "Warangal,Andhra Pradesh", value: "Warangal,Andhra Pradesh" },
  { label: "Yellandu,Andhra Pradesh", value: "Yellandu,Andhra Pradesh" },
  { label: "Yemmiganur,Andhra Pradesh", value: "Yemmiganur,Andhra Pradesh" },
  { label: "Yerraguntla,Andhra Pradesh", value: "Yerraguntla,Andhra Pradesh" },
  { label: "Zahirabad,Andhra Pradesh", value: "Zahirabad,Andhra Pradesh" },
  { label: "Rajampet,Andhra Pradesh", value: "Rajampet,Andhra Pradesh" },
  { label: "Along,Arunachal Pradesh", value: "Along,Arunachal Pradesh" },
  { label: "Bomdila,Arunachal Pradesh", value: "Bomdila,Arunachal Pradesh" },
  { label: "Itanagar,Arunachal Pradesh", value: "Itanagar,Arunachal Pradesh" },
  {
    label: "Naharlagun,Arunachal Pradesh",
    value: "Naharlagun,Arunachal Pradesh",
  },
  { label: "Pasighat,Arunachal Pradesh", value: "Pasighat,Arunachal Pradesh" },
  { label: "Abhayapuri,Assam", value: "Abhayapuri,Assam" },
  { label: "Amguri,Assam", value: "Amguri,Assam" },
  { label: "Anandnagaar,Assam", value: "Anandnagaar,Assam" },
  { label: "Barpeta,Assam", value: "Barpeta,Assam" },
  { label: "Barpeta Road,Assam", value: "Barpeta Road,Assam" },
  { label: "Bilasipara,Assam", value: "Bilasipara,Assam" },
  { label: "Bongaigaon,Assam", value: "Bongaigaon,Assam" },
  { label: "Dhekiajuli,Assam", value: "Dhekiajuli,Assam" },
  { label: "Dhubri,Assam", value: "Dhubri,Assam" },
  { label: "Dibrugarh,Assam", value: "Dibrugarh,Assam" },
  { label: "Digboi,Assam", value: "Digboi,Assam" },
  { label: "Diphu,Assam", value: "Diphu,Assam" },
  { label: "Dispur,Assam", value: "Dispur,Assam" },
  { label: "Gauripur,Assam", value: "Gauripur,Assam" },
  { label: "Goalpara,Assam", value: "Goalpara,Assam" },
  { label: "Golaghat,Assam", value: "Golaghat,Assam" },
  { label: "Guwahati,Assam", value: "Guwahati,Assam" },
  { label: "Haflong,Assam", value: "Haflong,Assam" },
  { label: "Hailakandi,Assam", value: "Hailakandi,Assam" },
  { label: "Hojai,Assam", value: "Hojai,Assam" },
  { label: "Jorhat,Assam", value: "Jorhat,Assam" },
  { label: "Karimganj,Assam", value: "Karimganj,Assam" },
  { label: "Kokrajhar,Assam", value: "Kokrajhar,Assam" },
  { label: "Lanka,Assam", value: "Lanka,Assam" },
  { label: "Lumding,Assam", value: "Lumding,Assam" },
  { label: "Mangaldoi,Assam", value: "Mangaldoi,Assam" },
  { label: "Mankachar,Assam", value: "Mankachar,Assam" },
  { label: "Margherita,Assam", value: "Margherita,Assam" },
  { label: "Mariani,Assam", value: "Mariani,Assam" },
  { label: "Marigaon,Assam", value: "Marigaon,Assam" },
  { label: "Nagaon,Assam", value: "Nagaon,Assam" },
  { label: "Nalbari,Assam", value: "Nalbari,Assam" },
  { label: "North Lakhimpur,Assam", value: "North Lakhimpur,Assam" },
  { label: "Rangia,Assam", value: "Rangia,Assam" },
  { label: "Sibsagar,Assam", value: "Sibsagar,Assam" },
  { label: "Silapathar,Assam", value: "Silapathar,Assam" },
  { label: "Silchar,Assam", value: "Silchar,Assam" },
  { label: "Tezpur,Assam", value: "Tezpur,Assam" },
  { label: "Tinsukia,Assam", value: "Tinsukia,Assam" },
  { label: "Amarpur,Bihar", value: "Amarpur,Bihar" },
  { label: "Araria,Bihar", value: "Araria,Bihar" },
  { label: "Areraj,Bihar", value: "Areraj,Bihar" },
  { label: "Arrah,Bihar", value: "Arrah,Bihar" },
  { label: "Asarganj,Bihar", value: "Asarganj,Bihar" },
  { label: "Aurangabad,Bihar", value: "Aurangabad,Bihar" },
  { label: "Bagaha,Bihar", value: "Bagaha,Bihar" },
  { label: "Bahadurganj,Bihar", value: "Bahadurganj,Bihar" },
  { label: "Bairgania,Bihar", value: "Bairgania,Bihar" },
  { label: "Bakhtiarpur,Bihar", value: "Bakhtiarpur,Bihar" },
  { label: "Banka,Bihar", value: "Banka,Bihar" },
  { label: "Banmankhi Bazar,Bihar", value: "Banmankhi Bazar,Bihar" },
  { label: "Barahiya,Bihar", value: "Barahiya,Bihar" },
  { label: "Barauli,Bihar", value: "Barauli,Bihar" },
  { label: "Barbigha,Bihar", value: "Barbigha,Bihar" },
  { label: "Barh,Bihar", value: "Barh,Bihar" },
  { label: "Begusarai,Bihar", value: "Begusarai,Bihar" },
  { label: "Behea,Bihar", value: "Behea,Bihar" },
  { label: "Bettiah,Bihar", value: "Bettiah,Bihar" },
  { label: "Bhabua,Bihar", value: "Bhabua,Bihar" },
  { label: "Bhagalpur,Bihar", value: "Bhagalpur,Bihar" },
  { label: "Bihar Sharif,Bihar", value: "Bihar Sharif,Bihar" },
  { label: "Bikramganj,Bihar", value: "Bikramganj,Bihar" },
  { label: "Bodh Gaya,Bihar", value: "Bodh Gaya,Bihar" },
  { label: "Buxar,Bihar", value: "Buxar,Bihar" },
  { label: "Chandan Bara,Bihar", value: "Chandan Bara,Bihar" },
  { label: "Chanpatia,Bihar", value: "Chanpatia,Bihar" },
  { label: "Chhapra,Bihar", value: "Chhapra,Bihar" },
  { label: "Colgong,Bihar", value: "Colgong,Bihar" },
  { label: "Dalsinghsarai,Bihar", value: "Dalsinghsarai,Bihar" },
  { label: "Darbhanga,Bihar", value: "Darbhanga,Bihar" },
  { label: "Daudnagar,Bihar", value: "Daudnagar,Bihar" },
  { label: "Dehri-on-Sone,Bihar", value: "Dehri-on-Sone,Bihar" },
  { label: "Dhaka,Bihar", value: "Dhaka,Bihar" },
  { label: "Dighwara,Bihar", value: "Dighwara,Bihar" },
  { label: "Dumraon,Bihar", value: "Dumraon,Bihar" },
  { label: "Fatwah,Bihar", value: "Fatwah,Bihar" },
  { label: "Forbesganj,Bihar", value: "Forbesganj,Bihar" },
  { label: "Gaya,Bihar", value: "Gaya,Bihar" },
  { label: "Gogri Jamalpur,Bihar", value: "Gogri Jamalpur,Bihar" },
  { label: "Gopalganj,Bihar", value: "Gopalganj,Bihar" },
  { label: "Hajipur,Bihar", value: "Hajipur,Bihar" },
  { label: "Hilsa,Bihar", value: "Hilsa,Bihar" },
  { label: "Hisua,Bihar", value: "Hisua,Bihar" },
  { label: "Islampur,Bihar", value: "Islampur,Bihar" },
  { label: "Jagdispur,Bihar", value: "Jagdispur,Bihar" },
  { label: "Jamalpur,Bihar", value: "Jamalpur,Bihar" },
  { label: "Jamui,Bihar", value: "Jamui,Bihar" },
  { label: "Jehanabad,Bihar", value: "Jehanabad,Bihar" },
  { label: "Jhajha,Bihar", value: "Jhajha,Bihar" },
  { label: "Jhanjharpur,Bihar", value: "Jhanjharpur,Bihar" },
  { label: "Jogabani,Bihar", value: "Jogabani,Bihar" },
  { label: "Kanti,Bihar", value: "Kanti,Bihar" },
  { label: "Katihar,Bihar", value: "Katihar,Bihar" },
  { label: "Khagaria,Bihar", value: "Khagaria,Bihar" },
  { label: "Kharagpur,Bihar", value: "Kharagpur,Bihar" },
  { label: "Kishanganj,Bihar", value: "Kishanganj,Bihar" },
  { label: "Lakhisarai,Bihar", value: "Lakhisarai,Bihar" },
  { label: "Lalganj,Bihar", value: "Lalganj,Bihar" },
  { label: "Madhepura,Bihar", value: "Madhepura,Bihar" },
  { label: "Madhubani,Bihar", value: "Madhubani,Bihar" },
  { label: "Maharajganj,Bihar", value: "Maharajganj,Bihar" },
  { label: "Mahnar Bazar,Bihar", value: "Mahnar Bazar,Bihar" },
  { label: "Makhdumpur,Bihar", value: "Makhdumpur,Bihar" },
  { label: "Maner,Bihar", value: "Maner,Bihar" },
  { label: "Manihari,Bihar", value: "Manihari,Bihar" },
  { label: "Marhaura,Bihar", value: "Marhaura,Bihar" },
  { label: "Masaurhi,Bihar", value: "Masaurhi,Bihar" },
  { label: "Mirganj,Bihar", value: "Mirganj,Bihar" },
  { label: "Mokameh,Bihar", value: "Mokameh,Bihar" },
  { label: "Motihari,Bihar", value: "Motihari,Bihar" },
  { label: "Motipur,Bihar", value: "Motipur,Bihar" },
  { label: "Munger,Bihar", value: "Munger,Bihar" },
  { label: "Murliganj,Bihar", value: "Murliganj,Bihar" },
  { label: "Muzaffarpur,Bihar", value: "Muzaffarpur,Bihar" },
  { label: "Narkatiaganj,Bihar", value: "Narkatiaganj,Bihar" },
  { label: "Naugachhia,Bihar", value: "Naugachhia,Bihar" },
  { label: "Nawada,Bihar", value: "Nawada,Bihar" },
  { label: "Nokha,Bihar", value: "Nokha,Bihar" },
  { label: "Patna,Bihar", value: "Patna,Bihar" },
  { label: "Piro,Bihar", value: "Piro,Bihar" },
  { label: "Purnia,Bihar", value: "Purnia,Bihar" },
  { label: "Rafiganj,Bihar", value: "Rafiganj,Bihar" },
  { label: "Rajgir,Bihar", value: "Rajgir,Bihar" },
  { label: "Ramnagar,Bihar", value: "Ramnagar,Bihar" },
  { label: "Raxaul Bazar,Bihar", value: "Raxaul Bazar,Bihar" },
  { label: "Revelganj,Bihar", value: "Revelganj,Bihar" },
  { label: "Rosera,Bihar", value: "Rosera,Bihar" },
  { label: "Saharsa,Bihar", value: "Saharsa,Bihar" },
  { label: "Samastipur,Bihar", value: "Samastipur,Bihar" },
  { label: "Sasaram,Bihar", value: "Sasaram,Bihar" },
  { label: "Sheikhpura,Bihar", value: "Sheikhpura,Bihar" },
  { label: "Sheohar,Bihar", value: "Sheohar,Bihar" },
  { label: "Sherghati,Bihar", value: "Sherghati,Bihar" },
  { label: "Silao,Bihar", value: "Silao,Bihar" },
  { label: "Sitamarhi,Bihar", value: "Sitamarhi,Bihar" },
  { label: "Siwan,Bihar", value: "Siwan,Bihar" },
  { label: "Sonepur,Bihar", value: "Sonepur,Bihar" },
  { label: "Sugauli,Bihar", value: "Sugauli,Bihar" },
  { label: "Sultanganj,Bihar", value: "Sultanganj,Bihar" },
  { label: "Supaul,Bihar", value: "Supaul,Bihar" },
  { label: "Warisaliganj,Bihar", value: "Warisaliganj,Bihar" },
  { label: "Ahiwara,Chhattisgarh", value: "Ahiwara,Chhattisgarh" },
  { label: "Akaltara,Chhattisgarh", value: "Akaltara,Chhattisgarh" },
  {
    label: "Ambagarh Chowki,Chhattisgarh",
    value: "Ambagarh Chowki,Chhattisgarh",
  },
  { label: "Ambikapur,Chhattisgarh", value: "Ambikapur,Chhattisgarh" },
  { label: "Arang,Chhattisgarh", value: "Arang,Chhattisgarh" },
  { label: "Bade Bacheli,Chhattisgarh", value: "Bade Bacheli,Chhattisgarh" },
  { label: "Balod,Chhattisgarh", value: "Balod,Chhattisgarh" },
  { label: "Baloda Bazar,Chhattisgarh", value: "Baloda Bazar,Chhattisgarh" },
  { label: "Bemetra,Chhattisgarh", value: "Bemetra,Chhattisgarh" },
  { label: "Bhatapara,Chhattisgarh", value: "Bhatapara,Chhattisgarh" },
  { label: "Bilaspur,Chhattisgarh", value: "Bilaspur,Chhattisgarh" },
  { label: "Birgaon,Chhattisgarh", value: "Birgaon,Chhattisgarh" },
  { label: "Champa,Chhattisgarh", value: "Champa,Chhattisgarh" },
  { label: "Chirmiri,Chhattisgarh", value: "Chirmiri,Chhattisgarh" },
  { label: "Dalli-Rajhara,Chhattisgarh", value: "Dalli-Rajhara,Chhattisgarh" },
  { label: "Dhamtari,Chhattisgarh", value: "Dhamtari,Chhattisgarh" },
  { label: "Dipka,Chhattisgarh", value: "Dipka,Chhattisgarh" },
  { label: "Dongargarh,Chhattisgarh", value: "Dongargarh,Chhattisgarh" },
  {
    label: "Durg-Bhilai Nagar,Chhattisgarh",
    value: "Durg-Bhilai Nagar,Chhattisgarh",
  },
  { label: "Gobranawapara,Chhattisgarh", value: "Gobranawapara,Chhattisgarh" },
  { label: "Jagdalpur,Chhattisgarh", value: "Jagdalpur,Chhattisgarh" },
  { label: "Janjgir,Chhattisgarh", value: "Janjgir,Chhattisgarh" },
  { label: "Jashpurnagar,Chhattisgarh", value: "Jashpurnagar,Chhattisgarh" },
  { label: "Kanker,Chhattisgarh", value: "Kanker,Chhattisgarh" },
  { label: "Kawardha,Chhattisgarh", value: "Kawardha,Chhattisgarh" },
  { label: "Kondagaon,Chhattisgarh", value: "Kondagaon,Chhattisgarh" },
  { label: "Korba,Chhattisgarh", value: "Korba,Chhattisgarh" },
  { label: "Mahasamund,Chhattisgarh", value: "Mahasamund,Chhattisgarh" },
  { label: "Mahendragarh,Chhattisgarh", value: "Mahendragarh,Chhattisgarh" },
  { label: "Mungeli,Chhattisgarh", value: "Mungeli,Chhattisgarh" },
  { label: "Naila Janjgir,Chhattisgarh", value: "Naila Janjgir,Chhattisgarh" },
  { label: "Raigarh,Chhattisgarh", value: "Raigarh,Chhattisgarh" },
  { label: "Raipur,Chhattisgarh", value: "Raipur,Chhattisgarh" },
  { label: "Rajnandgaon,Chhattisgarh", value: "Rajnandgaon,Chhattisgarh" },
  { label: "Sakti,Chhattisgarh", value: "Sakti,Chhattisgarh" },
  { label: "Tilda Newra,Chhattisgarh", value: "Tilda Newra,Chhattisgarh" },
  { label: "Amli,Dadra & Nagar Haveli", value: "Amli,Dadra & Nagar Haveli" },
  {
    label: "Silvassa,Dadra & Nagar Haveli",
    value: "Silvassa,Dadra & Nagar Haveli",
  },
  { label: "Daman and Diu,Daman & Diu", value: "Daman and Diu,Daman & Diu" },
  { label: "Asola,Delhi", value: "Asola,Delhi" },
  { label: "Delhi,Delhi", value: "Delhi,Delhi" },
  { label: "Aldona,Goa", value: "Aldona,Goa" },
  { label: "Curchorem Cacora,Goa", value: "Curchorem Cacora,Goa" },
  { label: "Madgaon,Goa", value: "Madgaon,Goa" },
  { label: "Mapusa,Goa", value: "Mapusa,Goa" },
  { label: "Margao,Goa", value: "Margao,Goa" },
  { label: "Marmagao,Goa", value: "Marmagao,Goa" },
  { label: "Panaji,Goa", value: "Panaji,Goa" },
  { label: "Ahmedabad,Gujarat", value: "Ahmedabad,Gujarat" },
  { label: "Amreli,Gujarat", value: "Amreli,Gujarat" },
  { label: "Anand,Gujarat", value: "Anand,Gujarat" },
  { label: "Ankleshwar,Gujarat", value: "Ankleshwar,Gujarat" },
  { label: "Bharuch,Gujarat", value: "Bharuch,Gujarat" },
  { label: "Bhavnagar,Gujarat", value: "Bhavnagar,Gujarat" },
  { label: "Bhuj,Gujarat", value: "Bhuj,Gujarat" },
  { label: "Cambay,Gujarat", value: "Cambay,Gujarat" },
  { label: "Dahod,Gujarat", value: "Dahod,Gujarat" },
  { label: "Deesa,Gujarat", value: "Deesa,Gujarat" },
  { label: "Dharampur, India", value: "Dharampur, India" },
  { label: "Dholka,Gujarat", value: "Dholka,Gujarat" },
  { label: "Gandhinagar,Gujarat", value: "Gandhinagar,Gujarat" },
  { label: "Godhra,Gujarat", value: "Godhra,Gujarat" },
  { label: "Himatnagar,Gujarat", value: "Himatnagar,Gujarat" },
  { label: "Idar,Gujarat", value: "Idar,Gujarat" },
  { label: "Jamnagar,Gujarat", value: "Jamnagar,Gujarat" },
  { label: "Junagadh,Gujarat", value: "Junagadh,Gujarat" },
  { label: "Kadi,Gujarat", value: "Kadi,Gujarat" },
  { label: "Kalavad,Gujarat", value: "Kalavad,Gujarat" },
  { label: "Kalol,Gujarat", value: "Kalol,Gujarat" },
  { label: "Kapadvanj,Gujarat", value: "Kapadvanj,Gujarat" },
  { label: "Karjan,Gujarat", value: "Karjan,Gujarat" },
  { label: "Keshod,Gujarat", value: "Keshod,Gujarat" },
  { label: "Khambhalia,Gujarat", value: "Khambhalia,Gujarat" },
  { label: "Khambhat,Gujarat", value: "Khambhat,Gujarat" },
  { label: "Kheda,Gujarat", value: "Kheda,Gujarat" },
  { label: "Khedbrahma,Gujarat", value: "Khedbrahma,Gujarat" },
  { label: "Kheralu,Gujarat", value: "Kheralu,Gujarat" },
  { label: "Kodinar,Gujarat", value: "Kodinar,Gujarat" },
  { label: "Lathi,Gujarat", value: "Lathi,Gujarat" },
  { label: "Limbdi,Gujarat", value: "Limbdi,Gujarat" },
  { label: "Lunawada,Gujarat", value: "Lunawada,Gujarat" },
  { label: "Mahesana,Gujarat", value: "Mahesana,Gujarat" },
  { label: "Mahuva,Gujarat", value: "Mahuva,Gujarat" },
  { label: "Manavadar,Gujarat", value: "Manavadar,Gujarat" },
  { label: "Mandvi,Gujarat", value: "Mandvi,Gujarat" },
  { label: "Mangrol,Gujarat", value: "Mangrol,Gujarat" },
  { label: "Mansa,Gujarat", value: "Mansa,Gujarat" },
  { label: "Mehmedabad,Gujarat", value: "Mehmedabad,Gujarat" },
  { label: "Modasa,Gujarat", value: "Modasa,Gujarat" },
  { label: "Morvi,Gujarat", value: "Morvi,Gujarat" },
  { label: "Nadiad,Gujarat", value: "Nadiad,Gujarat" },
  { label: "Navsari,Gujarat", value: "Navsari,Gujarat" },
  { label: "Padra,Gujarat", value: "Padra,Gujarat" },
  { label: "Palanpur,Gujarat", value: "Palanpur,Gujarat" },
  { label: "Palitana,Gujarat", value: "Palitana,Gujarat" },
  { label: "Pardi,Gujarat", value: "Pardi,Gujarat" },
  { label: "Patan,Gujarat", value: "Patan,Gujarat" },
  { label: "Petlad,Gujarat", value: "Petlad,Gujarat" },
  { label: "Porbandar,Gujarat", value: "Porbandar,Gujarat" },
  { label: "Radhanpur,Gujarat", value: "Radhanpur,Gujarat" },
  { label: "Rajkot,Gujarat", value: "Rajkot,Gujarat" },
  { label: "Rajpipla,Gujarat", value: "Rajpipla,Gujarat" },
  { label: "Rajula,Gujarat", value: "Rajula,Gujarat" },
  { label: "Ranavav,Gujarat", value: "Ranavav,Gujarat" },
  { label: "Rapar,Gujarat", value: "Rapar,Gujarat" },
  { label: "Salaya,Gujarat", value: "Salaya,Gujarat" },
  { label: "Sanand,Gujarat", value: "Sanand,Gujarat" },
  { label: "Savarkundla,Gujarat", value: "Savarkundla,Gujarat" },
  { label: "Sidhpur,Gujarat", value: "Sidhpur,Gujarat" },
  { label: "Sihor,Gujarat", value: "Sihor,Gujarat" },
  { label: "Songadh,Gujarat", value: "Songadh,Gujarat" },
  { label: "Surat,Gujarat", value: "Surat,Gujarat" },
  { label: "Talaja,Gujarat", value: "Talaja,Gujarat" },
  { label: "Thangadh,Gujarat", value: "Thangadh,Gujarat" },
  { label: "Tharad,Gujarat", value: "Tharad,Gujarat" },
  { label: "Umbergaon,Gujarat", value: "Umbergaon,Gujarat" },
  { label: "Umreth,Gujarat", value: "Umreth,Gujarat" },
  { label: "Una,Gujarat", value: "Una,Gujarat" },
  { label: "Unjha,Gujarat", value: "Unjha,Gujarat" },
  { label: "Upleta,Gujarat", value: "Upleta,Gujarat" },
  { label: "Vadnagar,Gujarat", value: "Vadnagar,Gujarat" },
  { label: "Vadodara,Gujarat", value: "Vadodara,Gujarat" },
  { label: "Valsad,Gujarat", value: "Valsad,Gujarat" },
  { label: "Vapi,Gujarat", value: "Vapi,Gujarat" },
  { label: "Veraval,Gujarat", value: "Veraval,Gujarat" },
  { label: "Vijapur,Gujarat", value: "Vijapur,Gujarat" },
  { label: "Viramgam,Gujarat", value: "Viramgam,Gujarat" },
  { label: "Visnagar,Gujarat", value: "Visnagar,Gujarat" },
  { label: "Vyara,Gujarat", value: "Vyara,Gujarat" },
  { label: "Wadhwan,Gujarat", value: "Wadhwan,Gujarat" },
  { label: "Wankaner,Gujarat", value: "Wankaner,Gujarat" },
  { label: "Adalaj,Gujrat", value: "Adalaj,Gujrat" },
  { label: "Adityana,Gujrat", value: "Adityana,Gujrat" },
  { label: "Alang,Gujrat", value: "Alang,Gujrat" },
  { label: "Ambaji,Gujrat", value: "Ambaji,Gujrat" },
  { label: "Ambaliyasan,Gujrat", value: "Ambaliyasan,Gujrat" },
  { label: "Andada,Gujrat", value: "Andada,Gujrat" },
  { label: "Anjar,Gujrat", value: "Anjar,Gujrat" },
  { label: "Anklav,Gujrat", value: "Anklav,Gujrat" },
  { label: "Antaliya,Gujrat", value: "Antaliya,Gujrat" },
  { label: "Arambhada,Gujrat", value: "Arambhada,Gujrat" },
  { label: "Atul,Gujrat", value: "Atul,Gujrat" },
  { label: "Ballabhgarh,Haryana", value: "Ballabhgarh,Haryana" },
  { label: "Ambala,Haryana", value: "Ambala,Haryana" },
  { label: "Asankhurd,Haryana", value: "Asankhurd,Haryana" },
  { label: "Assandh,Haryana", value: "Assandh,Haryana" },
  { label: "Ateli,Haryana", value: "Ateli,Haryana" },
  { label: "Babiyal,Haryana", value: "Babiyal,Haryana" },
  { label: "Bahadurgarh,Haryana", value: "Bahadurgarh,Haryana" },
  { label: "Barwala,Haryana", value: "Barwala,Haryana" },
  { label: "Bhiwani,Haryana", value: "Bhiwani,Haryana" },
  { label: "Charkhi Dadri,Haryana", value: "Charkhi Dadri,Haryana" },
  { label: "Cheeka,Haryana", value: "Cheeka,Haryana" },
  { label: "Ellenabad 2,Haryana", value: "Ellenabad 2,Haryana" },
  { label: "Faridabad,Haryana", value: "Faridabad,Haryana" },
  { label: "Fatehabad,Haryana", value: "Fatehabad,Haryana" },
  { label: "Ganaur,Haryana", value: "Ganaur,Haryana" },
  { label: "Gharaunda,Haryana", value: "Gharaunda,Haryana" },
  { label: "Gohana,Haryana", value: "Gohana,Haryana" },
  { label: "Gurgaon,Haryana", value: "Gurgaon,Haryana" },
  {
    label: "Haibat(Yamuna Nagar),Haryana",
    value: "Haibat(Yamuna Nagar),Haryana",
  },
  { label: "Hansi,Haryana", value: "Hansi,Haryana" },
  { label: "Hisar,Haryana", value: "Hisar,Haryana" },
  { label: "Hodal,Haryana", value: "Hodal,Haryana" },
  { label: "Jhajjar,Haryana", value: "Jhajjar,Haryana" },
  { label: "Jind,Haryana", value: "Jind,Haryana" },
  { label: "Kaithal,Haryana", value: "Kaithal,Haryana" },
  { label: "Kalan Wali,Haryana", value: "Kalan Wali,Haryana" },
  { label: "Kalka,Haryana", value: "Kalka,Haryana" },
  { label: "Karnal,Haryana", value: "Karnal,Haryana" },
  { label: "Ladwa,Haryana", value: "Ladwa,Haryana" },
  { label: "Mandi Dabwali,Haryana", value: "Mandi Dabwali,Haryana" },
  { label: "Narnaul,Haryana", value: "Narnaul,Haryana" },
  { label: "Narwana,Haryana", value: "Narwana,Haryana" },
  { label: "Palwal,Haryana", value: "Palwal,Haryana" },
  { label: "Panchkula,Haryana", value: "Panchkula,Haryana" },
  { label: "Panipat,Haryana", value: "Panipat,Haryana" },
  { label: "Pehowa,Haryana", value: "Pehowa,Haryana" },
  { label: "Pinjore,Haryana", value: "Pinjore,Haryana" },
  { label: "Rania,Haryana", value: "Rania,Haryana" },
  { label: "Ratia,Haryana", value: "Ratia,Haryana" },
  { label: "Rewari,Haryana", value: "Rewari,Haryana" },
  { label: "Rohtak,Haryana", value: "Rohtak,Haryana" },
  { label: "Safidon,Haryana", value: "Safidon,Haryana" },
  { label: "Samalkha,Haryana", value: "Samalkha,Haryana" },
  { label: "Shahbad,Haryana", value: "Shahbad,Haryana" },
  { label: "Sirsa,Haryana", value: "Sirsa,Haryana" },
  { label: "Sohna,Haryana", value: "Sohna,Haryana" },
  { label: "Sonipat,Haryana", value: "Sonipat,Haryana" },
  { label: "Taraori,Haryana", value: "Taraori,Haryana" },
  { label: "Thanesar,Haryana", value: "Thanesar,Haryana" },
  { label: "Tohana,Haryana", value: "Tohana,Haryana" },
  { label: "Yamunanagar,Haryana", value: "Yamunanagar,Haryana" },
  { label: "Arki,Himachal Pradesh", value: "Arki,Himachal Pradesh" },
  { label: "Baddi,Himachal Pradesh", value: "Baddi,Himachal Pradesh" },
  { label: "Bilaspur,Himachal Pradesh", value: "Bilaspur,Himachal Pradesh" },
  { label: "Chamba,Himachal Pradesh", value: "Chamba,Himachal Pradesh" },
  { label: "Dalhousie,Himachal Pradesh", value: "Dalhousie,Himachal Pradesh" },
  {
    label: "Dharamsala,Himachal Pradesh",
    value: "Dharamsala,Himachal Pradesh",
  },
  { label: "Hamirpur,Himachal Pradesh", value: "Hamirpur,Himachal Pradesh" },
  { label: "Mandi,Himachal Pradesh", value: "Mandi,Himachal Pradesh" },
  { label: "Nahan,Himachal Pradesh", value: "Nahan,Himachal Pradesh" },
  { label: "Shimla,Himachal Pradesh", value: "Shimla,Himachal Pradesh" },
  { label: "Solan,Himachal Pradesh", value: "Solan,Himachal Pradesh" },
  {
    label: "Sundarnagar,Himachal Pradesh",
    value: "Sundarnagar,Himachal Pradesh",
  },
  { label: "Jammu,Jammu & Kashmir", value: "Jammu,Jammu & Kashmir" },
  { label: "Achabbal,Jammu & Kashmir", value: "Achabbal,Jammu & Kashmir" },
  { label: "Akhnoor,Jammu & Kashmir", value: "Akhnoor,Jammu & Kashmir" },
  { label: "Anantnag,Jammu & Kashmir", value: "Anantnag,Jammu & Kashmir" },
  { label: "Arnia,Jammu & Kashmir", value: "Arnia,Jammu & Kashmir" },
  { label: "Awantipora,Jammu & Kashmir", value: "Awantipora,Jammu & Kashmir" },
  { label: "Bandipore,Jammu & Kashmir", value: "Bandipore,Jammu & Kashmir" },
  { label: "Baramula,Jammu & Kashmir", value: "Baramula,Jammu & Kashmir" },
  { label: "Kathua,Jammu & Kashmir", value: "Kathua,Jammu & Kashmir" },
  { label: "Leh,Jammu & Kashmir", value: "Leh,Jammu & Kashmir" },
  { label: "Punch,Jammu & Kashmir", value: "Punch,Jammu & Kashmir" },
  { label: "Rajauri,Jammu & Kashmir", value: "Rajauri,Jammu & Kashmir" },
  { label: "Sopore,Jammu & Kashmir", value: "Sopore,Jammu & Kashmir" },
  { label: "Srinagar,Jammu & Kashmir", value: "Srinagar,Jammu & Kashmir" },
  { label: "Udhampur,Jammu & Kashmir", value: "Udhampur,Jammu & Kashmir" },
  { label: "Amlabad,Jharkhand", value: "Amlabad,Jharkhand" },
  { label: "Ara,Jharkhand", value: "Ara,Jharkhand" },
  { label: "Barughutu,Jharkhand", value: "Barughutu,Jharkhand" },
  {
    label: "Bokaro Steel City,Jharkhand",
    value: "Bokaro Steel City,Jharkhand",
  },
  { label: "Chaibasa,Jharkhand", value: "Chaibasa,Jharkhand" },
  { label: "Chakradharpur,Jharkhand", value: "Chakradharpur,Jharkhand" },
  { label: "Chandrapura,Jharkhand", value: "Chandrapura,Jharkhand" },
  { label: "Chatra,Jharkhand", value: "Chatra,Jharkhand" },
  { label: "Chirkunda,Jharkhand", value: "Chirkunda,Jharkhand" },
  { label: "Churi,Jharkhand", value: "Churi,Jharkhand" },
  { label: "Daltonganj,Jharkhand", value: "Daltonganj,Jharkhand" },
  { label: "Deoghar,Jharkhand", value: "Deoghar,Jharkhand" },
  { label: "Dhanbad,Jharkhand", value: "Dhanbad,Jharkhand" },
  { label: "Dumka,Jharkhand", value: "Dumka,Jharkhand" },
  { label: "Garhwa,Jharkhand", value: "Garhwa,Jharkhand" },
  { label: "Ghatshila,Jharkhand", value: "Ghatshila,Jharkhand" },
  { label: "Giridih,Jharkhand", value: "Giridih,Jharkhand" },
  { label: "Godda,Jharkhand", value: "Godda,Jharkhand" },
  { label: "Gomoh,Jharkhand", value: "Gomoh,Jharkhand" },
  { label: "Gumia,Jharkhand", value: "Gumia,Jharkhand" },
  { label: "Gumla,Jharkhand", value: "Gumla,Jharkhand" },
  { label: "Hazaribag,Jharkhand", value: "Hazaribag,Jharkhand" },
  { label: "Hussainabad,Jharkhand", value: "Hussainabad,Jharkhand" },
  { label: "Jamshedpur,Jharkhand", value: "Jamshedpur,Jharkhand" },
  { label: "Jamtara,Jharkhand", value: "Jamtara,Jharkhand" },
  { label: "Jhumri Tilaiya,Jharkhand", value: "Jhumri Tilaiya,Jharkhand" },
  { label: "Khunti,Jharkhand", value: "Khunti,Jharkhand" },
  { label: "Lohardaga,Jharkhand", value: "Lohardaga,Jharkhand" },
  { label: "Madhupur,Jharkhand", value: "Madhupur,Jharkhand" },
  { label: "Mihijam,Jharkhand", value: "Mihijam,Jharkhand" },
  { label: "Musabani,Jharkhand", value: "Musabani,Jharkhand" },
  { label: "Pakaur,Jharkhand", value: "Pakaur,Jharkhand" },
  { label: "Patratu,Jharkhand", value: "Patratu,Jharkhand" },
  { label: "Phusro,Jharkhand", value: "Phusro,Jharkhand" },
  { label: "Ramngarh,Jharkhand", value: "Ramngarh,Jharkhand" },
  { label: "Ranchi,Jharkhand", value: "Ranchi,Jharkhand" },
  { label: "Sahibganj,Jharkhand", value: "Sahibganj,Jharkhand" },
  { label: "Saunda,Jharkhand", value: "Saunda,Jharkhand" },
  { label: "Simdega,Jharkhand", value: "Simdega,Jharkhand" },
  {
    label: "Tenu Dam-cum- Kathhara,Jharkhand",
    value: "Tenu Dam-cum- Kathhara,Jharkhand",
  },
  { label: "Arasikere,Karnataka", value: "Arasikere,Karnataka" },
  { label: "Bangalore,Karnataka", value: "Bangalore,Karnataka" },
  { label: "Belgaum,Karnataka", value: "Belgaum,Karnataka" },
  { label: "Bellary,Karnataka", value: "Bellary,Karnataka" },
  { label: "Chamrajnagar,Karnataka", value: "Chamrajnagar,Karnataka" },
  { label: "Chikkaballapur,Karnataka", value: "Chikkaballapur,Karnataka" },
  { label: "Chintamani,Karnataka", value: "Chintamani,Karnataka" },
  { label: "Chitradurga,Karnataka", value: "Chitradurga,Karnataka" },
  { label: "Gulbarga,Karnataka", value: "Gulbarga,Karnataka" },
  { label: "Gundlupet,Karnataka", value: "Gundlupet,Karnataka" },
  { label: "Hassan,Karnataka", value: "Hassan,Karnataka" },
  { label: "Hospet,Karnataka", value: "Hospet,Karnataka" },
  { label: "Hubli,Karnataka", value: "Hubli,Karnataka" },
  { label: "Karkala,Karnataka", value: "Karkala,Karnataka" },
  { label: "Karwar,Karnataka", value: "Karwar,Karnataka" },
  { label: "Kolar,Karnataka", value: "Kolar,Karnataka" },
  { label: "Kota,Karnataka", value: "Kota,Karnataka" },
  { label: "Lakshmeshwar,Karnataka", value: "Lakshmeshwar,Karnataka" },
  { label: "Lingsugur,Karnataka", value: "Lingsugur,Karnataka" },
  { label: "Maddur,Karnataka", value: "Maddur,Karnataka" },
  { label: "Madhugiri,Karnataka", value: "Madhugiri,Karnataka" },
  { label: "Madikeri,Karnataka", value: "Madikeri,Karnataka" },
  { label: "Magadi,Karnataka", value: "Magadi,Karnataka" },
  { label: "Mahalingpur,Karnataka", value: "Mahalingpur,Karnataka" },
  { label: "Malavalli,Karnataka", value: "Malavalli,Karnataka" },
  { label: "Malur,Karnataka", value: "Malur,Karnataka" },
  { label: "Mandya,Karnataka", value: "Mandya,Karnataka" },
  { label: "Mangalore,Karnataka", value: "Mangalore,Karnataka" },
  { label: "Manvi,Karnataka", value: "Manvi,Karnataka" },
  { label: "Mudalgi,Karnataka", value: "Mudalgi,Karnataka" },
  { label: "Mudbidri,Karnataka", value: "Mudbidri,Karnataka" },
  { label: "Muddebihal,Karnataka", value: "Muddebihal,Karnataka" },
  { label: "Mudhol,Karnataka", value: "Mudhol,Karnataka" },
  { label: "Mulbagal,Karnataka", value: "Mulbagal,Karnataka" },
  { label: "Mundargi,Karnataka", value: "Mundargi,Karnataka" },
  { label: "Mysore,Karnataka", value: "Mysore,Karnataka" },
  { label: "Nanjangud,Karnataka", value: "Nanjangud,Karnataka" },
  { label: "Pavagada,Karnataka", value: "Pavagada,Karnataka" },
  { label: "Puttur,Karnataka", value: "Puttur,Karnataka" },
  { label: "Rabkavi Banhatti,Karnataka", value: "Rabkavi Banhatti,Karnataka" },
  { label: "Raichur,Karnataka", value: "Raichur,Karnataka" },
  { label: "Ramanagaram,Karnataka", value: "Ramanagaram,Karnataka" },
  { label: "Ramdurg,Karnataka", value: "Ramdurg,Karnataka" },
  { label: "Ranibennur,Karnataka", value: "Ranibennur,Karnataka" },
  { label: "Robertson Pet,Karnataka", value: "Robertson Pet,Karnataka" },
  { label: "Ron,Karnataka", value: "Ron,Karnataka" },
  { label: "Sadalgi,Karnataka", value: "Sadalgi,Karnataka" },
  { label: "Sagar,Karnataka", value: "Sagar,Karnataka" },
  { label: "Sakleshpur,Karnataka", value: "Sakleshpur,Karnataka" },
  { label: "Sandur,Karnataka", value: "Sandur,Karnataka" },
  { label: "Sankeshwar,Karnataka", value: "Sankeshwar,Karnataka" },
  {
    label: "Saundatti-Yellamma,Karnataka",
    value: "Saundatti-Yellamma,Karnataka",
  },
  { label: "Savanur,Karnataka", value: "Savanur,Karnataka" },
  { label: "Sedam,Karnataka", value: "Sedam,Karnataka" },
  { label: "Shahabad,Karnataka", value: "Shahabad,Karnataka" },
  { label: "Shahpur,Karnataka", value: "Shahpur,Karnataka" },
  { label: "Shiggaon,Karnataka", value: "Shiggaon,Karnataka" },
  { label: "Shikapur,Karnataka", value: "Shikapur,Karnataka" },
  { label: "Shimoga,Karnataka", value: "Shimoga,Karnataka" },
  { label: "Shorapur,Karnataka", value: "Shorapur,Karnataka" },
  { label: "Shrirangapattana,Karnataka", value: "Shrirangapattana,Karnataka" },
  { label: "Sidlaghatta,Karnataka", value: "Sidlaghatta,Karnataka" },
  { label: "Sindgi,Karnataka", value: "Sindgi,Karnataka" },
  { label: "Sindhnur,Karnataka", value: "Sindhnur,Karnataka" },
  { label: "Sira,Karnataka", value: "Sira,Karnataka" },
  { label: "Sirsi,Karnataka", value: "Sirsi,Karnataka" },
  { label: "Siruguppa,Karnataka", value: "Siruguppa,Karnataka" },
  { label: "Srinivaspur,Karnataka", value: "Srinivaspur,Karnataka" },
  { label: "Talikota,Karnataka", value: "Talikota,Karnataka" },
  { label: "Tarikere,Karnataka", value: "Tarikere,Karnataka" },
  { label: "Tekkalakota,Karnataka", value: "Tekkalakota,Karnataka" },
  { label: "Terdal,Karnataka", value: "Terdal,Karnataka" },
  { label: "Tiptur,Karnataka", value: "Tiptur,Karnataka" },
  { label: "Tumkur,Karnataka", value: "Tumkur,Karnataka" },
  { label: "Udupi,Karnataka", value: "Udupi,Karnataka" },
  { label: "Vijayapura,Karnataka", value: "Vijayapura,Karnataka" },
  { label: "Wadi,Karnataka", value: "Wadi,Karnataka" },
  { label: "Yadgir,Karnataka", value: "Yadgir,Karnataka" },
  { label: "Adoor,Kerala", value: "Adoor,Kerala" },
  { label: "Akathiyoor,Kerala", value: "Akathiyoor,Kerala" },
  { label: "Alappuzha,Kerala", value: "Alappuzha,Kerala" },
  { label: "Ancharakandy,Kerala", value: "Ancharakandy,Kerala" },
  { label: "Aroor,Kerala", value: "Aroor,Kerala" },
  { label: "Ashtamichira,Kerala", value: "Ashtamichira,Kerala" },
  { label: "Attingal,Kerala", value: "Attingal,Kerala" },
  { label: "Avinissery,Kerala", value: "Avinissery,Kerala" },
  { label: "Chalakudy,Kerala", value: "Chalakudy,Kerala" },
  { label: "Changanassery,Kerala", value: "Changanassery,Kerala" },
  { label: "Chendamangalam,Kerala", value: "Chendamangalam,Kerala" },
  { label: "Chengannur,Kerala", value: "Chengannur,Kerala" },
  { label: "Cherthala,Kerala", value: "Cherthala,Kerala" },
  { label: "Cheruthazham,Kerala", value: "Cheruthazham,Kerala" },
  {
    label: "Chittur-Thathamangalam,Kerala",
    value: "Chittur-Thathamangalam,Kerala",
  },
  { label: "Chockli,Kerala", value: "Chockli,Kerala" },
  { label: "Erattupetta,Kerala", value: "Erattupetta,Kerala" },
  { label: "Guruvayoor,Kerala", value: "Guruvayoor,Kerala" },
  { label: "Irinjalakuda,Kerala", value: "Irinjalakuda,Kerala" },
  { label: "Kadirur,Kerala", value: "Kadirur,Kerala" },
  { label: "Kalliasseri,Kerala", value: "Kalliasseri,Kerala" },
  { label: "Kalpetta,Kerala", value: "Kalpetta,Kerala" },
  { label: "Kanhangad,Kerala", value: "Kanhangad,Kerala" },
  { label: "Kanjikkuzhi,Kerala", value: "Kanjikkuzhi,Kerala" },
  { label: "Kannur,Kerala", value: "Kannur,Kerala" },
  { label: "Kasaragod,Kerala", value: "Kasaragod,Kerala" },
  { label: "Kayamkulam,Kerala", value: "Kayamkulam,Kerala" },
  { label: "Kochi,Kerala", value: "Kochi,Kerala" },
  { label: "Kodungallur,Kerala", value: "Kodungallur,Kerala" },
  { label: "Kollam,Kerala", value: "Kollam,Kerala" },
  { label: "Koothuparamba,Kerala", value: "Koothuparamba,Kerala" },
  { label: "Kothamangalam,Kerala", value: "Kothamangalam,Kerala" },
  { label: "Kottayam,Kerala", value: "Kottayam,Kerala" },
  { label: "Kozhikode,Kerala", value: "Kozhikode,Kerala" },
  { label: "Kunnamkulam,Kerala", value: "Kunnamkulam,Kerala" },
  { label: "Malappuram,Kerala", value: "Malappuram,Kerala" },
  { label: "Mattannur,Kerala", value: "Mattannur,Kerala" },
  { label: "Mavelikkara,Kerala", value: "Mavelikkara,Kerala" },
  { label: "Mavoor,Kerala", value: "Mavoor,Kerala" },
  { label: "Muvattupuzha,Kerala", value: "Muvattupuzha,Kerala" },
  { label: "Nedumangad,Kerala", value: "Nedumangad,Kerala" },
  { label: "Neyyattinkara,Kerala", value: "Neyyattinkara,Kerala" },
  { label: "Ottappalam,Kerala", value: "Ottappalam,Kerala" },
  { label: "Palai,Kerala", value: "Palai,Kerala" },
  { label: "Palakkad,Kerala", value: "Palakkad,Kerala" },
  { label: "Panniyannur,Kerala", value: "Panniyannur,Kerala" },
  { label: "Pappinisseri,Kerala", value: "Pappinisseri,Kerala" },
  { label: "Paravoor,Kerala", value: "Paravoor,Kerala" },
  { label: "Pathanamthitta,Kerala", value: "Pathanamthitta,Kerala" },
  { label: "Payyannur,Kerala", value: "Payyannur,Kerala" },
  { label: "Peringathur,Kerala", value: "Peringathur,Kerala" },
  { label: "Perinthalmanna,Kerala", value: "Perinthalmanna,Kerala" },
  { label: "Perumbavoor,Kerala", value: "Perumbavoor,Kerala" },
  { label: "Ponnani,Kerala", value: "Ponnani,Kerala" },
  { label: "Punalur,Kerala", value: "Punalur,Kerala" },
  { label: "Quilandy,Kerala", value: "Quilandy,Kerala" },
  { label: "Shoranur,Kerala", value: "Shoranur,Kerala" },
  { label: "Taliparamba,Kerala", value: "Taliparamba,Kerala" },
  { label: "Thiruvalla,Kerala", value: "Thiruvalla,Kerala" },
  { label: "Thiruvananthapuram,Kerala", value: "Thiruvananthapuram,Kerala" },
  { label: "Thodupuzha,Kerala", value: "Thodupuzha,Kerala" },
  { label: "Thrissur,Kerala", value: "Thrissur,Kerala" },
  { label: "Tirur,Kerala", value: "Tirur,Kerala" },
  { label: "Vadakara,Kerala", value: "Vadakara,Kerala" },
  { label: "Vaikom,Kerala", value: "Vaikom,Kerala" },
  { label: "Varkala,Kerala", value: "Varkala,Kerala" },
  { label: "Kavaratti,Lakshadweep", value: "Kavaratti,Lakshadweep" },
  { label: "Ashok Nagar,Madhya Pradesh", value: "Ashok Nagar,Madhya Pradesh" },
  { label: "Balaghat,Madhya Pradesh", value: "Balaghat,Madhya Pradesh" },
  { label: "Betul,Madhya Pradesh", value: "Betul,Madhya Pradesh" },
  { label: "Bhopal,Madhya Pradesh", value: "Bhopal,Madhya Pradesh" },
  { label: "Burhanpur,Madhya Pradesh", value: "Burhanpur,Madhya Pradesh" },
  { label: "Chhatarpur,Madhya Pradesh", value: "Chhatarpur,Madhya Pradesh" },
  { label: "Dabra,Madhya Pradesh", value: "Dabra,Madhya Pradesh" },
  { label: "Datia,Madhya Pradesh", value: "Datia,Madhya Pradesh" },
  { label: "Dewas,Madhya Pradesh", value: "Dewas,Madhya Pradesh" },
  { label: "Dhar,Madhya Pradesh", value: "Dhar,Madhya Pradesh" },
  { label: "Fatehabad,Madhya Pradesh", value: "Fatehabad,Madhya Pradesh" },
  { label: "Gwalior,Madhya Pradesh", value: "Gwalior,Madhya Pradesh" },
  { label: "Indore,Madhya Pradesh", value: "Indore,Madhya Pradesh" },
  { label: "Itarsi,Madhya Pradesh", value: "Itarsi,Madhya Pradesh" },
  { label: "Jabalpur,Madhya Pradesh", value: "Jabalpur,Madhya Pradesh" },
  { label: "Katni,Madhya Pradesh", value: "Katni,Madhya Pradesh" },
  { label: "Kotma,Madhya Pradesh", value: "Kotma,Madhya Pradesh" },
  { label: "Lahar,Madhya Pradesh", value: "Lahar,Madhya Pradesh" },
  { label: "Lundi,Madhya Pradesh", value: "Lundi,Madhya Pradesh" },
  { label: "Maharajpur,Madhya Pradesh", value: "Maharajpur,Madhya Pradesh" },
  { label: "Mahidpur,Madhya Pradesh", value: "Mahidpur,Madhya Pradesh" },
  { label: "Maihar,Madhya Pradesh", value: "Maihar,Madhya Pradesh" },
  { label: "Malajkhand,Madhya Pradesh", value: "Malajkhand,Madhya Pradesh" },
  { label: "Manasa,Madhya Pradesh", value: "Manasa,Madhya Pradesh" },
  { label: "Manawar,Madhya Pradesh", value: "Manawar,Madhya Pradesh" },
  { label: "Mandideep,Madhya Pradesh", value: "Mandideep,Madhya Pradesh" },
  { label: "Mandla,Madhya Pradesh", value: "Mandla,Madhya Pradesh" },
  { label: "Mandsaur,Madhya Pradesh", value: "Mandsaur,Madhya Pradesh" },
  { label: "Mauganj,Madhya Pradesh", value: "Mauganj,Madhya Pradesh" },
  {
    label: "Mhow Cantonment,Madhya Pradesh",
    value: "Mhow Cantonment,Madhya Pradesh",
  },
  { label: "Mhowgaon,Madhya Pradesh", value: "Mhowgaon,Madhya Pradesh" },
  { label: "Morena,Madhya Pradesh", value: "Morena,Madhya Pradesh" },
  { label: "Multai,Madhya Pradesh", value: "Multai,Madhya Pradesh" },
  { label: "Murwara,Madhya Pradesh", value: "Murwara,Madhya Pradesh" },
  { label: "Nagda,Madhya Pradesh", value: "Nagda,Madhya Pradesh" },
  { label: "Nainpur,Madhya Pradesh", value: "Nainpur,Madhya Pradesh" },
  {
    label: "Narsinghgarh,Madhya Pradesh",
    value: "Narsinghgarh,Madhya Pradesh",
  },
  { label: "Neemuch,Madhya Pradesh", value: "Neemuch,Madhya Pradesh" },
  { label: "Nepanagar,Madhya Pradesh", value: "Nepanagar,Madhya Pradesh" },
  { label: "Niwari,Madhya Pradesh", value: "Niwari,Madhya Pradesh" },
  { label: "Nowgong,Madhya Pradesh", value: "Nowgong,Madhya Pradesh" },
  { label: "Nowrozabad,Madhya Pradesh", value: "Nowrozabad,Madhya Pradesh" },
  { label: "Pachore,Madhya Pradesh", value: "Pachore,Madhya Pradesh" },
  { label: "Pali,Madhya Pradesh", value: "Pali,Madhya Pradesh" },
  { label: "Panagar,Madhya Pradesh", value: "Panagar,Madhya Pradesh" },
  { label: "Pandhurna,Madhya Pradesh", value: "Pandhurna,Madhya Pradesh" },
  { label: "Panna,Madhya Pradesh", value: "Panna,Madhya Pradesh" },
  { label: "Pasan,Madhya Pradesh", value: "Pasan,Madhya Pradesh" },
  { label: "Pipariya,Madhya Pradesh", value: "Pipariya,Madhya Pradesh" },
  { label: "Pithampur,Madhya Pradesh", value: "Pithampur,Madhya Pradesh" },
  { label: "Porsa,Madhya Pradesh", value: "Porsa,Madhya Pradesh" },
  { label: "Prithvipur,Madhya Pradesh", value: "Prithvipur,Madhya Pradesh" },
  {
    label: "Raghogarh-Vijaypur,Madhya Pradesh",
    value: "Raghogarh-Vijaypur,Madhya Pradesh",
  },
  { label: "Rahatgarh,Madhya Pradesh", value: "Rahatgarh,Madhya Pradesh" },
  { label: "Raisen,Madhya Pradesh", value: "Raisen,Madhya Pradesh" },
  { label: "Rajgarh,Madhya Pradesh", value: "Rajgarh,Madhya Pradesh" },
  { label: "Ratlam,Madhya Pradesh", value: "Ratlam,Madhya Pradesh" },
  { label: "Rau,Madhya Pradesh", value: "Rau,Madhya Pradesh" },
  { label: "Rehli,Madhya Pradesh", value: "Rehli,Madhya Pradesh" },
  { label: "Rewa,Madhya Pradesh", value: "Rewa,Madhya Pradesh" },
  { label: "Sabalgarh,Madhya Pradesh", value: "Sabalgarh,Madhya Pradesh" },
  { label: "Sagar,Madhya Pradesh", value: "Sagar,Madhya Pradesh" },
  { label: "Sanawad,Madhya Pradesh", value: "Sanawad,Madhya Pradesh" },
  { label: "Sarangpur,Madhya Pradesh", value: "Sarangpur,Madhya Pradesh" },
  { label: "Sarni,Madhya Pradesh", value: "Sarni,Madhya Pradesh" },
  { label: "Satna,Madhya Pradesh", value: "Satna,Madhya Pradesh" },
  { label: "Sausar,Madhya Pradesh", value: "Sausar,Madhya Pradesh" },
  { label: "Sehore,Madhya Pradesh", value: "Sehore,Madhya Pradesh" },
  { label: "Sendhwa,Madhya Pradesh", value: "Sendhwa,Madhya Pradesh" },
  { label: "Seoni,Madhya Pradesh", value: "Seoni,Madhya Pradesh" },
  { label: "Seoni-Malwa,Madhya Pradesh", value: "Seoni-Malwa,Madhya Pradesh" },
  { label: "Shahdol,Madhya Pradesh", value: "Shahdol,Madhya Pradesh" },
  { label: "Shajapur,Madhya Pradesh", value: "Shajapur,Madhya Pradesh" },
  { label: "Shamgarh,Madhya Pradesh", value: "Shamgarh,Madhya Pradesh" },
  { label: "Sheopur,Madhya Pradesh", value: "Sheopur,Madhya Pradesh" },
  { label: "Shivpuri,Madhya Pradesh", value: "Shivpuri,Madhya Pradesh" },
  { label: "Shujalpur,Madhya Pradesh", value: "Shujalpur,Madhya Pradesh" },
  { label: "Sidhi,Madhya Pradesh", value: "Sidhi,Madhya Pradesh" },
  { label: "Sihora,Madhya Pradesh", value: "Sihora,Madhya Pradesh" },
  { label: "Singrauli,Madhya Pradesh", value: "Singrauli,Madhya Pradesh" },
  { label: "Sironj,Madhya Pradesh", value: "Sironj,Madhya Pradesh" },
  { label: "Sohagpur,Madhya Pradesh", value: "Sohagpur,Madhya Pradesh" },
  { label: "Tarana,Madhya Pradesh", value: "Tarana,Madhya Pradesh" },
  { label: "Tikamgarh,Madhya Pradesh", value: "Tikamgarh,Madhya Pradesh" },
  { label: "Ujhani,Madhya Pradesh", value: "Ujhani,Madhya Pradesh" },
  { label: "Ujjain,Madhya Pradesh", value: "Ujjain,Madhya Pradesh" },
  { label: "Umaria,Madhya Pradesh", value: "Umaria,Madhya Pradesh" },
  { label: "Vidisha,Madhya Pradesh", value: "Vidisha,Madhya Pradesh" },
  { label: "Wara Seoni,Madhya Pradesh", value: "Wara Seoni,Madhya Pradesh" },
  { label: "Ahmednagar,Maharashtra", value: "Ahmednagar,Maharashtra" },
  { label: "Akola,Maharashtra", value: "Akola,Maharashtra" },
  { label: "Amravati,Maharashtra", value: "Amravati,Maharashtra" },
  { label: "Aurangabad,Maharashtra", value: "Aurangabad,Maharashtra" },
  { label: "Baramati,Maharashtra", value: "Baramati,Maharashtra" },
  { label: "Chalisgaon,Maharashtra", value: "Chalisgaon,Maharashtra" },
  { label: "Chinchani,Maharashtra", value: "Chinchani,Maharashtra" },
  { label: "Devgarh,Maharashtra", value: "Devgarh,Maharashtra" },
  { label: "Dhule,Maharashtra", value: "Dhule,Maharashtra" },
  { label: "Dombivli,Maharashtra", value: "Dombivli,Maharashtra" },
  { label: "Durgapur,Maharashtra", value: "Durgapur,Maharashtra" },
  { label: "Ichalkaranji,Maharashtra", value: "Ichalkaranji,Maharashtra" },
  { label: "Jalna,Maharashtra", value: "Jalna,Maharashtra" },
  { label: "Kalyan,Maharashtra", value: "Kalyan,Maharashtra" },
  { label: "Latur,Maharashtra", value: "Latur,Maharashtra" },
  { label: "Loha,Maharashtra", value: "Loha,Maharashtra" },
  { label: "Lonar,Maharashtra", value: "Lonar,Maharashtra" },
  { label: "Lonavla,Maharashtra", value: "Lonavla,Maharashtra" },
  { label: "Mahad,Maharashtra", value: "Mahad,Maharashtra" },
  { label: "Mahuli,Maharashtra", value: "Mahuli,Maharashtra" },
  { label: "Malegaon,Maharashtra", value: "Malegaon,Maharashtra" },
  { label: "Malkapur,Maharashtra", value: "Malkapur,Maharashtra" },
  { label: "Manchar,Maharashtra", value: "Manchar,Maharashtra" },
  { label: "Mangalvedhe,Maharashtra", value: "Mangalvedhe,Maharashtra" },
  { label: "Mangrulpir,Maharashtra", value: "Mangrulpir,Maharashtra" },
  { label: "Manjlegaon,Maharashtra", value: "Manjlegaon,Maharashtra" },
  { label: "Manmad,Maharashtra", value: "Manmad,Maharashtra" },
  { label: "Manwath,Maharashtra", value: "Manwath,Maharashtra" },
  { label: "Mehkar,Maharashtra", value: "Mehkar,Maharashtra" },
  { label: "Mhaswad,Maharashtra", value: "Mhaswad,Maharashtra" },
  { label: "Miraj,Maharashtra", value: "Miraj,Maharashtra" },
  { label: "Morshi,Maharashtra", value: "Morshi,Maharashtra" },
  { label: "Mukhed,Maharashtra", value: "Mukhed,Maharashtra" },
  { label: "Mul,Maharashtra", value: "Mul,Maharashtra" },
  { label: "Mumbai,Maharashtra", value: "Mumbai,Maharashtra" },
  { label: "Murtijapur,Maharashtra", value: "Murtijapur,Maharashtra" },
  { label: "Nagpur,Maharashtra", value: "Nagpur,Maharashtra" },
  { label: "Nalasopara,Maharashtra", value: "Nalasopara,Maharashtra" },
  { label: "Nanded-Waghala,Maharashtra", value: "Nanded-Waghala,Maharashtra" },
  { label: "Nandgaon,Maharashtra", value: "Nandgaon,Maharashtra" },
  { label: "Nandura,Maharashtra", value: "Nandura,Maharashtra" },
  { label: "Nandurbar,Maharashtra", value: "Nandurbar,Maharashtra" },
  { label: "Narkhed,Maharashtra", value: "Narkhed,Maharashtra" },
  { label: "Nashik,Maharashtra", value: "Nashik,Maharashtra" },
  { label: "Navi Mumbai,Maharashtra", value: "Navi Mumbai,Maharashtra" },
  { label: "Nawapur,Maharashtra", value: "Nawapur,Maharashtra" },
  { label: "Nilanga,Maharashtra", value: "Nilanga,Maharashtra" },
  { label: "Osmanabad,Maharashtra", value: "Osmanabad,Maharashtra" },
  { label: "Ozar,Maharashtra", value: "Ozar,Maharashtra" },
  { label: "Pachora,Maharashtra", value: "Pachora,Maharashtra" },
  { label: "Paithan,Maharashtra", value: "Paithan,Maharashtra" },
  { label: "Palghar,Maharashtra", value: "Palghar,Maharashtra" },
  { label: "Pandharkaoda,Maharashtra", value: "Pandharkaoda,Maharashtra" },
  { label: "Pandharpur,Maharashtra", value: "Pandharpur,Maharashtra" },
  { label: "Panvel,Maharashtra", value: "Panvel,Maharashtra" },
  { label: "Parbhani,Maharashtra", value: "Parbhani,Maharashtra" },
  { label: "Parli,Maharashtra", value: "Parli,Maharashtra" },
  { label: "Parola,Maharashtra", value: "Parola,Maharashtra" },
  { label: "Partur,Maharashtra", value: "Partur,Maharashtra" },
  { label: "Pathardi,Maharashtra", value: "Pathardi,Maharashtra" },
  { label: "Pathri,Maharashtra", value: "Pathri,Maharashtra" },
  { label: "Patur,Maharashtra", value: "Patur,Maharashtra" },
  { label: "Pauni,Maharashtra", value: "Pauni,Maharashtra" },
  { label: "Pen,Maharashtra", value: "Pen,Maharashtra" },
  { label: "Phaltan,Maharashtra", value: "Phaltan,Maharashtra" },
  { label: "Pulgaon,Maharashtra", value: "Pulgaon,Maharashtra" },
  { label: "Pune,Maharashtra", value: "Pune,Maharashtra" },
  { label: "Purna,Maharashtra", value: "Purna,Maharashtra" },
  { label: "Pusad,Maharashtra", value: "Pusad,Maharashtra" },
  { label: "Rahuri,Maharashtra", value: "Rahuri,Maharashtra" },
  { label: "Rajura,Maharashtra", value: "Rajura,Maharashtra" },
  { label: "Ramtek,Maharashtra", value: "Ramtek,Maharashtra" },
  { label: "Ratnagiri,Maharashtra", value: "Ratnagiri,Maharashtra" },
  { label: "Raver,Maharashtra", value: "Raver,Maharashtra" },
  { label: "Risod,Maharashtra", value: "Risod,Maharashtra" },
  { label: "Sailu,Maharashtra", value: "Sailu,Maharashtra" },
  { label: "Sangamner,Maharashtra", value: "Sangamner,Maharashtra" },
  { label: "Sangli,Maharashtra", value: "Sangli,Maharashtra" },
  { label: "Sangole,Maharashtra", value: "Sangole,Maharashtra" },
  { label: "Sasvad,Maharashtra", value: "Sasvad,Maharashtra" },
  { label: "Satana,Maharashtra", value: "Satana,Maharashtra" },
  { label: "Satara,Maharashtra", value: "Satara,Maharashtra" },
  { label: "Savner,Maharashtra", value: "Savner,Maharashtra" },
  { label: "Sawantwadi,Maharashtra", value: "Sawantwadi,Maharashtra" },
  { label: "Shahade,Maharashtra", value: "Shahade,Maharashtra" },
  { label: "Shegaon,Maharashtra", value: "Shegaon,Maharashtra" },
  { label: "Shendurjana,Maharashtra", value: "Shendurjana,Maharashtra" },
  { label: "Shirdi,Maharashtra", value: "Shirdi,Maharashtra" },
  {
    label: "Shirpur-Warwade,Maharashtra",
    value: "Shirpur-Warwade,Maharashtra",
  },
  { label: "Shirur,Maharashtra", value: "Shirur,Maharashtra" },
  { label: "Shrigonda,Maharashtra", value: "Shrigonda,Maharashtra" },
  { label: "Shrirampur,Maharashtra", value: "Shrirampur,Maharashtra" },
  { label: "Sillod,Maharashtra", value: "Sillod,Maharashtra" },
  { label: "Sinnar,Maharashtra", value: "Sinnar,Maharashtra" },
  { label: "Solapur,Maharashtra", value: "Solapur,Maharashtra" },
  { label: "Soyagaon,Maharashtra", value: "Soyagaon,Maharashtra" },
  {
    label: "Talegaon Dabhade,Maharashtra",
    value: "Talegaon Dabhade,Maharashtra",
  },
  { label: "Talode,Maharashtra", value: "Talode,Maharashtra" },
  { label: "Tasgaon,Maharashtra", value: "Tasgaon,Maharashtra" },
  { label: "Tirora,Maharashtra", value: "Tirora,Maharashtra" },
  { label: "Tuljapur,Maharashtra", value: "Tuljapur,Maharashtra" },
  { label: "Tumsar,Maharashtra", value: "Tumsar,Maharashtra" },
  { label: "Uran,Maharashtra", value: "Uran,Maharashtra" },
  { label: "Uran Islampur,Maharashtra", value: "Uran Islampur,Maharashtra" },
  { label: "Wadgaon Road,Maharashtra", value: "Wadgaon Road,Maharashtra" },
  { label: "Wai,Maharashtra", value: "Wai,Maharashtra" },
  { label: "Wani,Maharashtra", value: "Wani,Maharashtra" },
  { label: "Wardha,Maharashtra", value: "Wardha,Maharashtra" },
  { label: "Warora,Maharashtra", value: "Warora,Maharashtra" },
  { label: "Warud,Maharashtra", value: "Warud,Maharashtra" },
  { label: "Washim,Maharashtra", value: "Washim,Maharashtra" },
  { label: "Yevla,Maharashtra", value: "Yevla,Maharashtra" },
  { label: "Uchgaon,Maharashtra", value: "Uchgaon,Maharashtra" },
  { label: "Udgir,Maharashtra", value: "Udgir,Maharashtra" },
  { label: "Umarga,Maharastra", value: "Umarga,Maharastra" },
  { label: "Umarkhed,Maharastra", value: "Umarkhed,Maharastra" },
  { label: "Umred,Maharastra", value: "Umred,Maharastra" },
  { label: "Vadgaon Kasba,Maharastra", value: "Vadgaon Kasba,Maharastra" },
  { label: "Vaijapur,Maharastra", value: "Vaijapur,Maharastra" },
  { label: "Vasai,Maharastra", value: "Vasai,Maharastra" },
  { label: "Virar,Maharastra", value: "Virar,Maharastra" },
  { label: "Vita,Maharastra", value: "Vita,Maharastra" },
  { label: "Yavatmal,Maharastra", value: "Yavatmal,Maharastra" },
  { label: "Yawal,Maharastra", value: "Yawal,Maharastra" },
  { label: "Imphal,Manipur", value: "Imphal,Manipur" },
  { label: "Kakching,Manipur", value: "Kakching,Manipur" },
  { label: "Lilong,Manipur", value: "Lilong,Manipur" },
  { label: "Mayang Imphal,Manipur", value: "Mayang Imphal,Manipur" },
  { label: "Thoubal,Manipur", value: "Thoubal,Manipur" },
  { label: "Jowai,Meghalaya", value: "Jowai,Meghalaya" },
  { label: "Nongstoin,Meghalaya", value: "Nongstoin,Meghalaya" },
  { label: "Shillong,Meghalaya", value: "Shillong,Meghalaya" },
  { label: "Tura,Meghalaya", value: "Tura,Meghalaya" },
  { label: "Aizawl,Mizoram", value: "Aizawl,Mizoram" },
  { label: "Champhai,Mizoram", value: "Champhai,Mizoram" },
  { label: "Lunglei,Mizoram", value: "Lunglei,Mizoram" },
  { label: "Saiha,Mizoram", value: "Saiha,Mizoram" },
  { label: "Dimapur,Nagaland", value: "Dimapur,Nagaland" },
  { label: "Kohima,Nagaland", value: "Kohima,Nagaland" },
  { label: "Mokokchung,Nagaland", value: "Mokokchung,Nagaland" },
  { label: "Tuensang,Nagaland", value: "Tuensang,Nagaland" },
  { label: "Wokha,Nagaland", value: "Wokha,Nagaland" },
  { label: "Zunheboto,Nagaland", value: "Zunheboto,Nagaland" },
  { label: "Anandapur,Orissa", value: "Anandapur,Orissa" },
  { label: "Anugul,Orissa", value: "Anugul,Orissa" },
  { label: "Asika,Orissa", value: "Asika,Orissa" },
  { label: "Balangir,Orissa", value: "Balangir,Orissa" },
  { label: "Balasore,Orissa", value: "Balasore,Orissa" },
  { label: "Baleshwar,Orissa", value: "Baleshwar,Orissa" },
  { label: "Bamra,Orissa", value: "Bamra,Orissa" },
  { label: "Barbil,Orissa", value: "Barbil,Orissa" },
  { label: "Bargarh,Orissa", value: "Bargarh,Orissa" },
  { label: "Baripada,Orissa", value: "Baripada,Orissa" },
  { label: "Basudebpur,Orissa", value: "Basudebpur,Orissa" },
  { label: "Belpahar,Orissa", value: "Belpahar,Orissa" },
  { label: "Bhadrak,Orissa", value: "Bhadrak,Orissa" },
  { label: "Bhawanipatna,Orissa", value: "Bhawanipatna,Orissa" },
  { label: "Bhuban,Orissa", value: "Bhuban,Orissa" },
  { label: "Bhubaneswar,Orissa", value: "Bhubaneswar,Orissa" },
  { label: "Biramitrapur,Orissa", value: "Biramitrapur,Orissa" },
  { label: "Brahmapur,Orissa", value: "Brahmapur,Orissa" },
  { label: "Brajrajnagar,Orissa", value: "Brajrajnagar,Orissa" },
  { label: "Byasanagar,Orissa", value: "Byasanagar,Orissa" },
  { label: "Cuttack,Orissa", value: "Cuttack,Orissa" },
  { label: "Debagarh,Orissa", value: "Debagarh,Orissa" },
  { label: "Dhenkanal,Orissa", value: "Dhenkanal,Orissa" },
  { label: "Gunupur,Orissa", value: "Gunupur,Orissa" },
  { label: "Hinjilicut,Orissa", value: "Hinjilicut,Orissa" },
  { label: "Jagatsinghapur,Orissa", value: "Jagatsinghapur,Orissa" },
  { label: "Jajapur,Orissa", value: "Jajapur,Orissa" },
  { label: "Jaleswar,Orissa", value: "Jaleswar,Orissa" },
  { label: "Jatani,Orissa", value: "Jatani,Orissa" },
  { label: "Jeypur,Orissa", value: "Jeypur,Orissa" },
  { label: "Jharsuguda,Orissa", value: "Jharsuguda,Orissa" },
  { label: "Joda,Orissa", value: "Joda,Orissa" },
  { label: "Kantabanji,Orissa", value: "Kantabanji,Orissa" },
  { label: "Karanjia,Orissa", value: "Karanjia,Orissa" },
  { label: "Kendrapara,Orissa", value: "Kendrapara,Orissa" },
  { label: "Kendujhar,Orissa", value: "Kendujhar,Orissa" },
  { label: "Khordha,Orissa", value: "Khordha,Orissa" },
  { label: "Koraput,Orissa", value: "Koraput,Orissa" },
  { label: "Malkangiri,Orissa", value: "Malkangiri,Orissa" },
  { label: "Nabarangapur,Orissa", value: "Nabarangapur,Orissa" },
  { label: "Paradip,Orissa", value: "Paradip,Orissa" },
  { label: "Parlakhemundi,Orissa", value: "Parlakhemundi,Orissa" },
  { label: "Pattamundai,Orissa", value: "Pattamundai,Orissa" },
  { label: "Phulabani,Orissa", value: "Phulabani,Orissa" },
  { label: "Puri,Orissa", value: "Puri,Orissa" },
  { label: "Rairangpur,Orissa", value: "Rairangpur,Orissa" },
  { label: "Rajagangapur,Orissa", value: "Rajagangapur,Orissa" },
  { label: "Raurkela,Orissa", value: "Raurkela,Orissa" },
  { label: "Rayagada,Orissa", value: "Rayagada,Orissa" },
  { label: "Sambalpur,Orissa", value: "Sambalpur,Orissa" },
  { label: "Soro,Orissa", value: "Soro,Orissa" },
  { label: "Sunabeda,Orissa", value: "Sunabeda,Orissa" },
  { label: "Sundargarh,Orissa", value: "Sundargarh,Orissa" },
  { label: "Talcher,Orissa", value: "Talcher,Orissa" },
  { label: "Titlagarh,Orissa", value: "Titlagarh,Orissa" },
  { label: "Umarkote,Orissa", value: "Umarkote,Orissa" },
  { label: "Karaikal,Pondicherry", value: "Karaikal,Pondicherry" },
  { label: "Mahe,Pondicherry", value: "Mahe,Pondicherry" },
  { label: "Pondicherry,Pondicherry", value: "Pondicherry,Pondicherry" },
  { label: "Yanam,Pondicherry", value: "Yanam,Pondicherry" },
  { label: "Ahmedgarh,Punjab", value: "Ahmedgarh,Punjab" },
  { label: "Amritsar,Punjab", value: "Amritsar,Punjab" },
  { label: "Barnala,Punjab", value: "Barnala,Punjab" },
  { label: "Batala,Punjab", value: "Batala,Punjab" },
  { label: "Bathinda,Punjab", value: "Bathinda,Punjab" },
  { label: "Bhagha Purana,Punjab", value: "Bhagha Purana,Punjab" },
  { label: "Budhlada,Punjab", value: "Budhlada,Punjab" },
  { label: "Chandigarh,Punjab", value: "Chandigarh,Punjab" },
  { label: "Dasua,Punjab", value: "Dasua,Punjab" },
  { label: "Dhuri,Punjab", value: "Dhuri,Punjab" },
  { label: "Dinanagar,Punjab", value: "Dinanagar,Punjab" },
  { label: "Faridkot,Punjab", value: "Faridkot,Punjab" },
  { label: "Fazilka,Punjab", value: "Fazilka,Punjab" },
  { label: "Firozpur,Punjab", value: "Firozpur,Punjab" },
  { label: "Firozpur Cantt.,Punjab", value: "Firozpur Cantt.,Punjab" },
  { label: "Giddarbaha,Punjab", value: "Giddarbaha,Punjab" },
  { label: "Gobindgarh,Punjab", value: "Gobindgarh,Punjab" },
  { label: "Gurdaspur,Punjab", value: "Gurdaspur,Punjab" },
  { label: "Hoshiarpur,Punjab", value: "Hoshiarpur,Punjab" },
  { label: "Jagraon,Punjab", value: "Jagraon,Punjab" },
  { label: "Jaitu,Punjab", value: "Jaitu,Punjab" },
  { label: "Jalalabad,Punjab", value: "Jalalabad,Punjab" },
  { label: "Jalandhar,Punjab", value: "Jalandhar,Punjab" },
  { label: "Jalandhar Cantt.,Punjab", value: "Jalandhar Cantt.,Punjab" },
  { label: "Jandiala,Punjab", value: "Jandiala,Punjab" },
  { label: "Kapurthala,Punjab", value: "Kapurthala,Punjab" },
  { label: "Karoran,Punjab", value: "Karoran,Punjab" },
  { label: "Kartarpur,Punjab", value: "Kartarpur,Punjab" },
  { label: "Khanna,Punjab", value: "Khanna,Punjab" },
  { label: "Kharar,Punjab", value: "Kharar,Punjab" },
  { label: "Kot Kapura,Punjab", value: "Kot Kapura,Punjab" },
  { label: "Kurali,Punjab", value: "Kurali,Punjab" },
  { label: "Longowal,Punjab", value: "Longowal,Punjab" },
  { label: "Ludhiana,Punjab", value: "Ludhiana,Punjab" },
  { label: "Malerkotla,Punjab", value: "Malerkotla,Punjab" },
  { label: "Malout,Punjab", value: "Malout,Punjab" },
  { label: "Mansa,Punjab", value: "Mansa,Punjab" },
  { label: "Maur,Punjab", value: "Maur,Punjab" },
  { label: "Moga,Punjab", value: "Moga,Punjab" },
  { label: "Mohali,Punjab", value: "Mohali,Punjab" },
  { label: "Morinda,Punjab", value: "Morinda,Punjab" },
  { label: "Mukerian,Punjab", value: "Mukerian,Punjab" },
  { label: "Muktsar,Punjab", value: "Muktsar,Punjab" },
  { label: "Nabha,Punjab", value: "Nabha,Punjab" },
  { label: "Nakodar,Punjab", value: "Nakodar,Punjab" },
  { label: "Nangal,Punjab", value: "Nangal,Punjab" },
  { label: "Nawanshahr,Punjab", value: "Nawanshahr,Punjab" },
  { label: "Pathankot,Punjab", value: "Pathankot,Punjab" },
  { label: "Patiala,Punjab", value: "Patiala,Punjab" },
  { label: "Patran,Punjab", value: "Patran,Punjab" },
  { label: "Patti,Punjab", value: "Patti,Punjab" },
  { label: "Phagwara,Punjab", value: "Phagwara,Punjab" },
  { label: "Phillaur,Punjab", value: "Phillaur,Punjab" },
  { label: "Qadian,Punjab", value: "Qadian,Punjab" },
  { label: "Raikot,Punjab", value: "Raikot,Punjab" },
  { label: "Rajpura,Punjab", value: "Rajpura,Punjab" },
  { label: "Rampura Phul,Punjab", value: "Rampura Phul,Punjab" },
  { label: "Rupnagar,Punjab", value: "Rupnagar,Punjab" },
  { label: "Samana,Punjab", value: "Samana,Punjab" },
  { label: "Sangrur,Punjab", value: "Sangrur,Punjab" },
  {
    label: "Sirhind Fatehgarh Sahib,Punjab",
    value: "Sirhind Fatehgarh Sahib,Punjab",
  },
  { label: "Sujanpur,Punjab", value: "Sujanpur,Punjab" },
  { label: "Sunam,Punjab", value: "Sunam,Punjab" },
  { label: "Talwara,Punjab", value: "Talwara,Punjab" },
  { label: "Tarn Taran,Punjab", value: "Tarn Taran,Punjab" },
  { label: "Urmar Tanda,Punjab", value: "Urmar Tanda,Punjab" },
  { label: "Zira,Punjab", value: "Zira,Punjab" },
  { label: "Zirakpur,Punjab", value: "Zirakpur,Punjab" },
  { label: "Bali,Rajasthan", value: "Bali,Rajasthan" },
  { label: "Banswara,Rajastan", value: "Banswara,Rajastan" },
  { label: "Ajmer,Rajasthan", value: "Ajmer,Rajasthan" },
  { label: "Alwar,Rajasthan", value: "Alwar,Rajasthan" },
  { label: "Bandikui,Rajasthan", value: "Bandikui,Rajasthan" },
  { label: "Baran,Rajasthan", value: "Baran,Rajasthan" },
  { label: "Barmer,Rajasthan", value: "Barmer,Rajasthan" },
  { label: "Bikaner,Rajasthan", value: "Bikaner,Rajasthan" },
  { label: "Fatehpur,Rajasthan", value: "Fatehpur,Rajasthan" },
  { label: "Jaipur,Rajasthan", value: "Jaipur,Rajasthan" },
  { label: "Jaisalmer,Rajasthan", value: "Jaisalmer,Rajasthan" },
  { label: "Jodhpur,Rajasthan", value: "Jodhpur,Rajasthan" },
  { label: "Kota,Rajasthan", value: "Kota,Rajasthan" },
  { label: "Lachhmangarh,Rajasthan", value: "Lachhmangarh,Rajasthan" },
  { label: "Ladnu,Rajasthan", value: "Ladnu,Rajasthan" },
  { label: "Lakheri,Rajasthan", value: "Lakheri,Rajasthan" },
  { label: "Lalsot,Rajasthan", value: "Lalsot,Rajasthan" },
  { label: "Losal,Rajasthan", value: "Losal,Rajasthan" },
  { label: "Makrana,Rajasthan", value: "Makrana,Rajasthan" },
  { label: "Malpura,Rajasthan", value: "Malpura,Rajasthan" },
  { label: "Mandalgarh,Rajasthan", value: "Mandalgarh,Rajasthan" },
  { label: "Mandawa,Rajasthan", value: "Mandawa,Rajasthan" },
  { label: "Mangrol,Rajasthan", value: "Mangrol,Rajasthan" },
  { label: "Merta City,Rajasthan", value: "Merta City,Rajasthan" },
  { label: "Mount Abu,Rajasthan", value: "Mount Abu,Rajasthan" },
  { label: "Nadbai,Rajasthan", value: "Nadbai,Rajasthan" },
  { label: "Nagar,Rajasthan", value: "Nagar,Rajasthan" },
  { label: "Nagaur,Rajasthan", value: "Nagaur,Rajasthan" },
  { label: "Nargund,Rajasthan", value: "Nargund,Rajasthan" },
  { label: "Nasirabad,Rajasthan", value: "Nasirabad,Rajasthan" },
  { label: "Nathdwara,Rajasthan", value: "Nathdwara,Rajasthan" },
  { label: "Navalgund,Rajasthan", value: "Navalgund,Rajasthan" },
  { label: "Nawalgarh,Rajasthan", value: "Nawalgarh,Rajasthan" },
  { label: "Neem-Ka-Thana,Rajasthan", value: "Neem-Ka-Thana,Rajasthan" },
  { label: "Nelamangala,Rajasthan", value: "Nelamangala,Rajasthan" },
  { label: "Nimbahera,Rajasthan", value: "Nimbahera,Rajasthan" },
  { label: "Nipani,Rajasthan", value: "Nipani,Rajasthan" },
  { label: "Niwai,Rajasthan", value: "Niwai,Rajasthan" },
  { label: "Nohar,Rajasthan", value: "Nohar,Rajasthan" },
  { label: "Nokha,Rajasthan", value: "Nokha,Rajasthan" },
  { label: "Pali,Rajasthan", value: "Pali,Rajasthan" },
  { label: "Phalodi,Rajasthan", value: "Phalodi,Rajasthan" },
  { label: "Phulera,Rajasthan", value: "Phulera,Rajasthan" },
  { label: "Pilani,Rajasthan", value: "Pilani,Rajasthan" },
  { label: "Pilibanga,Rajasthan", value: "Pilibanga,Rajasthan" },
  { label: "Pindwara,Rajasthan", value: "Pindwara,Rajasthan" },
  { label: "Pipar City,Rajasthan", value: "Pipar City,Rajasthan" },
  { label: "Prantij,Rajasthan", value: "Prantij,Rajasthan" },
  { label: "Pratapgarh,Rajasthan", value: "Pratapgarh,Rajasthan" },
  { label: "Raisinghnagar,Rajasthan", value: "Raisinghnagar,Rajasthan" },
  { label: "Rajakhera,Rajasthan", value: "Rajakhera,Rajasthan" },
  { label: "Rajaldesar,Rajasthan", value: "Rajaldesar,Rajasthan" },
  { label: "Rajgarh (Alwar),Rajasthan", value: "Rajgarh (Alwar),Rajasthan" },
  { label: "Rajgarh (Churu,Rajasthan", value: "Rajgarh (Churu,Rajasthan" },
  { label: "Rajsamand,Rajasthan", value: "Rajsamand,Rajasthan" },
  { label: "Ramganj Mandi,Rajasthan", value: "Ramganj Mandi,Rajasthan" },
  { label: "Ramngarh,Rajasthan", value: "Ramngarh,Rajasthan" },
  { label: "Ratangarh,Rajasthan", value: "Ratangarh,Rajasthan" },
  { label: "Rawatbhata,Rajasthan", value: "Rawatbhata,Rajasthan" },
  { label: "Rawatsar,Rajasthan", value: "Rawatsar,Rajasthan" },
  { label: "Reengus,Rajasthan", value: "Reengus,Rajasthan" },
  { label: "Sadri,Rajasthan", value: "Sadri,Rajasthan" },
  { label: "Sadulshahar,Rajasthan", value: "Sadulshahar,Rajasthan" },
  { label: "Sagwara,Rajasthan", value: "Sagwara,Rajasthan" },
  { label: "Sambhar,Rajasthan", value: "Sambhar,Rajasthan" },
  { label: "Sanchore,Rajasthan", value: "Sanchore,Rajasthan" },
  { label: "Sangaria,Rajasthan", value: "Sangaria,Rajasthan" },
  { label: "Sardarshahar,Rajasthan", value: "Sardarshahar,Rajasthan" },
  { label: "Sawai Madhopur,Rajasthan", value: "Sawai Madhopur,Rajasthan" },
  { label: "Shahpura,Rajasthan", value: "Shahpura,Rajasthan" },
  { label: "Sheoganj,Rajasthan", value: "Sheoganj,Rajasthan" },
  { label: "Sikar,Rajasthan", value: "Sikar,Rajasthan" },
  { label: "Sirohi,Rajasthan", value: "Sirohi,Rajasthan" },
  { label: "Sojat,Rajasthan", value: "Sojat,Rajasthan" },
  { label: "Sri Madhopur,Rajasthan", value: "Sri Madhopur,Rajasthan" },
  { label: "Sujangarh,Rajasthan", value: "Sujangarh,Rajasthan" },
  { label: "Sumerpur,Rajasthan", value: "Sumerpur,Rajasthan" },
  { label: "Suratgarh,Rajasthan", value: "Suratgarh,Rajasthan" },
  { label: "Taranagar,Rajasthan", value: "Taranagar,Rajasthan" },
  { label: "Todabhim,Rajasthan", value: "Todabhim,Rajasthan" },
  { label: "Todaraisingh,Rajasthan", value: "Todaraisingh,Rajasthan" },
  { label: "Tonk,Rajasthan", value: "Tonk,Rajasthan" },
  { label: "Udaipur,Rajasthan", value: "Udaipur,Rajasthan" },
  { label: "Udaipurwati,Rajasthan", value: "Udaipurwati,Rajasthan" },
  { label: "Vijainagar,Rajasthan", value: "Vijainagar,Rajasthan" },
  { label: "Gangtok,Sikkim", value: "Gangtok,Sikkim" },
  { label: "Calcutta,West Bengal", value: "Calcutta,West Bengal" },
  { label: "Arakkonam,Tamil Nadu", value: "Arakkonam,Tamil Nadu" },
  { label: "Arcot,Tamil Nadu", value: "Arcot,Tamil Nadu" },
  { label: "Aruppukkottai,Tamil Nadu", value: "Aruppukkottai,Tamil Nadu" },
  { label: "Bhavani,Tamil Nadu", value: "Bhavani,Tamil Nadu" },
  { label: "Chengalpattu,Tamil Nadu", value: "Chengalpattu,Tamil Nadu" },
  { label: "Chennai,Tamil Nadu", value: "Chennai,Tamil Nadu" },
  { label: "Chinna salem,Tamil nadu", value: "Chinna salem,Tamil nadu" },
  { label: "Coimbatore,Tamil Nadu", value: "Coimbatore,Tamil Nadu" },
  { label: "Coonoor,Tamil Nadu", value: "Coonoor,Tamil Nadu" },
  { label: "Cuddalore,Tamil Nadu", value: "Cuddalore,Tamil Nadu" },
  { label: "Dharmapuri,Tamil Nadu", value: "Dharmapuri,Tamil Nadu" },
  { label: "Dindigul,Tamil Nadu", value: "Dindigul,Tamil Nadu" },
  { label: "Erode,Tamil Nadu", value: "Erode,Tamil Nadu" },
  { label: "Gudalur,Tamil Nadu", value: "Gudalur,Tamil Nadu" },
  { label: "Kanchipuram,Tamil Nadu", value: "Kanchipuram,Tamil Nadu" },
  { label: "Karaikudi,Tamil Nadu", value: "Karaikudi,Tamil Nadu" },
  { label: "Karungal,Tamil Nadu", value: "Karungal,Tamil Nadu" },
  { label: "Karur,Tamil Nadu", value: "Karur,Tamil Nadu" },
  { label: "Kollankodu,Tamil Nadu", value: "Kollankodu,Tamil Nadu" },
  { label: "Lalgudi,Tamil Nadu", value: "Lalgudi,Tamil Nadu" },
  { label: "Madurai,Tamil Nadu", value: "Madurai,Tamil Nadu" },
  { label: "Nagapattinam,Tamil Nadu", value: "Nagapattinam,Tamil Nadu" },
  { label: "Nagercoil,Tamil Nadu", value: "Nagercoil,Tamil Nadu" },
  { label: "Namagiripettai,Tamil Nadu", value: "Namagiripettai,Tamil Nadu" },
  { label: "Namakkal,Tamil Nadu", value: "Namakkal,Tamil Nadu" },
  {
    label: "Nandivaram-Guduvancheri,Tamil Nadu",
    value: "Nandivaram-Guduvancheri,Tamil Nadu",
  },
  { label: "Nanjikottai,Tamil Nadu", value: "Nanjikottai,Tamil Nadu" },
  { label: "Natham,Tamil Nadu", value: "Natham,Tamil Nadu" },
  { label: "Nellikuppam,Tamil Nadu", value: "Nellikuppam,Tamil Nadu" },
  { label: "Neyveli,Tamil Nadu", value: "Neyveli,Tamil Nadu" },
  { label: "O Valley,Tamil Nadu", value: "O Valley,Tamil Nadu" },
  { label: "Oddanchatram,Tamil Nadu", value: "Oddanchatram,Tamil Nadu" },
  { label: "P.N.Patti,Tamil Nadu", value: "P.N.Patti,Tamil Nadu" },
  { label: "Pacode,Tamil Nadu", value: "Pacode,Tamil Nadu" },
  { label: "Padmanabhapuram,Tamil Nadu", value: "Padmanabhapuram,Tamil Nadu" },
  { label: "Palani,Tamil Nadu", value: "Palani,Tamil Nadu" },
  { label: "Palladam,Tamil Nadu", value: "Palladam,Tamil Nadu" },
  { label: "Pallapatti,Tamil Nadu", value: "Pallapatti,Tamil Nadu" },
  { label: "Pallikonda,Tamil Nadu", value: "Pallikonda,Tamil Nadu" },
  { label: "Panagudi,Tamil Nadu", value: "Panagudi,Tamil Nadu" },
  { label: "Panruti,Tamil Nadu", value: "Panruti,Tamil Nadu" },
  { label: "Paramakudi,Tamil Nadu", value: "Paramakudi,Tamil Nadu" },
  { label: "Parangipettai,Tamil Nadu", value: "Parangipettai,Tamil Nadu" },
  { label: "Pattukkottai,Tamil Nadu", value: "Pattukkottai,Tamil Nadu" },
  { label: "Perambalur,Tamil Nadu", value: "Perambalur,Tamil Nadu" },
  { label: "Peravurani,Tamil Nadu", value: "Peravurani,Tamil Nadu" },
  { label: "Periyakulam,Tamil Nadu", value: "Periyakulam,Tamil Nadu" },
  { label: "Periyasemur,Tamil Nadu", value: "Periyasemur,Tamil Nadu" },
  { label: "Pernampattu,Tamil Nadu", value: "Pernampattu,Tamil Nadu" },
  { label: "Pollachi,Tamil Nadu", value: "Pollachi,Tamil Nadu" },
  { label: "Polur,Tamil Nadu", value: "Polur,Tamil Nadu" },
  { label: "Ponneri,Tamil Nadu", value: "Ponneri,Tamil Nadu" },
  { label: "Pudukkottai,Tamil Nadu", value: "Pudukkottai,Tamil Nadu" },
  { label: "Pudupattinam,Tamil Nadu", value: "Pudupattinam,Tamil Nadu" },
  { label: "Puliyankudi,Tamil Nadu", value: "Puliyankudi,Tamil Nadu" },
  { label: "Punjaipugalur,Tamil Nadu", value: "Punjaipugalur,Tamil Nadu" },
  { label: "Rajapalayam,Tamil Nadu", value: "Rajapalayam,Tamil Nadu" },
  { label: "Ramanathapuram,Tamil Nadu", value: "Ramanathapuram,Tamil Nadu" },
  { label: "Rameshwaram,Tamil Nadu", value: "Rameshwaram,Tamil Nadu" },
  { label: "Rasipuram,Tamil Nadu", value: "Rasipuram,Tamil Nadu" },
  { label: "Salem,Tamil Nadu", value: "Salem,Tamil Nadu" },
  { label: "Sankarankoil,Tamil Nadu", value: "Sankarankoil,Tamil Nadu" },
  { label: "Sankari,Tamil Nadu", value: "Sankari,Tamil Nadu" },
  { label: "Sathyamangalam,Tamil Nadu", value: "Sathyamangalam,Tamil Nadu" },
  { label: "Sattur,Tamil Nadu", value: "Sattur,Tamil Nadu" },
  { label: "Shenkottai,Tamil Nadu", value: "Shenkottai,Tamil Nadu" },
  { label: "Sholavandan,Tamil Nadu", value: "Sholavandan,Tamil Nadu" },
  { label: "Sholingur,Tamil Nadu", value: "Sholingur,Tamil Nadu" },
  { label: "Sirkali,Tamil Nadu", value: "Sirkali,Tamil Nadu" },
  { label: "Sivaganga,Tamil Nadu", value: "Sivaganga,Tamil Nadu" },
  { label: "Sivagiri,Tamil Nadu", value: "Sivagiri,Tamil Nadu" },
  { label: "Sivakasi,Tamil Nadu", value: "Sivakasi,Tamil Nadu" },
  { label: "Srivilliputhur,Tamil Nadu", value: "Srivilliputhur,Tamil Nadu" },
  { label: "Surandai,Tamil Nadu", value: "Surandai,Tamil Nadu" },
  { label: "Suriyampalayam,Tamil Nadu", value: "Suriyampalayam,Tamil Nadu" },
  { label: "Tenkasi,Tamil Nadu", value: "Tenkasi,Tamil Nadu" },
  { label: "Thammampatti,Tamil Nadu", value: "Thammampatti,Tamil Nadu" },
  { label: "Thanjavur,Tamil Nadu", value: "Thanjavur,Tamil Nadu" },
  { label: "Tharamangalam,Tamil Nadu", value: "Tharamangalam,Tamil Nadu" },
  { label: "Tharangambadi,Tamil Nadu", value: "Tharangambadi,Tamil Nadu" },
  {
    label: "Theni Allinagaram,Tamil Nadu",
    value: "Theni Allinagaram,Tamil Nadu",
  },
  { label: "Thirumangalam,Tamil Nadu", value: "Thirumangalam,Tamil Nadu" },
  { label: "Thirunindravur,Tamil Nadu", value: "Thirunindravur,Tamil Nadu" },
  { label: "Thiruparappu,Tamil Nadu", value: "Thiruparappu,Tamil Nadu" },
  { label: "Thirupuvanam,Tamil Nadu", value: "Thirupuvanam,Tamil Nadu" },
  {
    label: "Thiruthuraipoondi,Tamil Nadu",
    value: "Thiruthuraipoondi,Tamil Nadu",
  },
  { label: "Thiruvallur,Tamil Nadu", value: "Thiruvallur,Tamil Nadu" },
  { label: "Thiruvarur,Tamil Nadu", value: "Thiruvarur,Tamil Nadu" },
  { label: "Thoothukudi,Tamil Nadu", value: "Thoothukudi,Tamil Nadu" },
  { label: "Thuraiyur,Tamil Nadu", value: "Thuraiyur,Tamil Nadu" },
  { label: "Tindivanam,Tamil Nadu", value: "Tindivanam,Tamil Nadu" },
  { label: "Tiruchendur,Tamil Nadu", value: "Tiruchendur,Tamil Nadu" },
  { label: "Tiruchengode,Tamil Nadu", value: "Tiruchengode,Tamil Nadu" },
  { label: "Tiruchirappalli,Tamil Nadu", value: "Tiruchirappalli,Tamil Nadu" },
  { label: "Tirukalukundram,Tamil Nadu", value: "Tirukalukundram,Tamil Nadu" },
  { label: "Tirukkoyilur,Tamil Nadu", value: "Tirukkoyilur,Tamil Nadu" },
  { label: "Tirunelveli,Tamil Nadu", value: "Tirunelveli,Tamil Nadu" },
  { label: "Tirupathur,Tamil Nadu", value: "Tirupathur,Tamil Nadu" },
  { label: "Tiruppur,Tamil Nadu", value: "Tiruppur,Tamil Nadu" },
  { label: "Tiruttani,Tamil Nadu", value: "Tiruttani,Tamil Nadu" },
  { label: "Tiruvannamalai,Tamil Nadu", value: "Tiruvannamalai,Tamil Nadu" },
  { label: "Tiruvethipuram,Tamil Nadu", value: "Tiruvethipuram,Tamil Nadu" },
  { label: "Tittakudi,Tamil Nadu", value: "Tittakudi,Tamil Nadu" },
  { label: "Udhagamandalam,Tamil Nadu", value: "Udhagamandalam,Tamil Nadu" },
  { label: "Udumalaipettai,Tamil Nadu", value: "Udumalaipettai,Tamil Nadu" },
  { label: "Unnamalaikadai,Tamil Nadu", value: "Unnamalaikadai,Tamil Nadu" },
  { label: "Usilampatti,Tamil Nadu", value: "Usilampatti,Tamil Nadu" },
  { label: "Uthamapalayam,Tamil Nadu", value: "Uthamapalayam,Tamil Nadu" },
  { label: "Uthiramerur,Tamil Nadu", value: "Uthiramerur,Tamil Nadu" },
  { label: "Vadakkuvalliyur,Tamil Nadu", value: "Vadakkuvalliyur,Tamil Nadu" },
  { label: "Vadalur,Tamil Nadu", value: "Vadalur,Tamil Nadu" },
  { label: "Vadipatti,Tamil Nadu", value: "Vadipatti,Tamil Nadu" },
  { label: "Valparai,Tamil Nadu", value: "Valparai,Tamil Nadu" },
  { label: "Vandavasi,Tamil Nadu", value: "Vandavasi,Tamil Nadu" },
  { label: "Vaniyambadi,Tamil Nadu", value: "Vaniyambadi,Tamil Nadu" },
  { label: "Vedaranyam,Tamil Nadu", value: "Vedaranyam,Tamil Nadu" },
  { label: "Vellakoil,Tamil Nadu", value: "Vellakoil,Tamil Nadu" },
  { label: "Vellore,Tamil Nadu", value: "Vellore,Tamil Nadu" },
  {
    label: "Vikramasingapuram,Tamil Nadu",
    value: "Vikramasingapuram,Tamil Nadu",
  },
  { label: "Viluppuram,Tamil Nadu", value: "Viluppuram,Tamil Nadu" },
  { label: "Virudhachalam,Tamil Nadu", value: "Virudhachalam,Tamil Nadu" },
  { label: "Virudhunagar,Tamil Nadu", value: "Virudhunagar,Tamil Nadu" },
  { label: "Viswanatham,Tamil Nadu", value: "Viswanatham,Tamil Nadu" },
  { label: "Agartala,Tripura", value: "Agartala,Tripura" },
  { label: "Badharghat,Tripura", value: "Badharghat,Tripura" },
  { label: "Dharmanagar,Tripura", value: "Dharmanagar,Tripura" },
  { label: "Indranagar,Tripura", value: "Indranagar,Tripura" },
  { label: "Jogendranagar,Tripura", value: "Jogendranagar,Tripura" },
  { label: "Kailasahar,Tripura", value: "Kailasahar,Tripura" },
  { label: "Khowai,Tripura", value: "Khowai,Tripura" },
  { label: "Pratapgarh,Tripura", value: "Pratapgarh,Tripura" },
  { label: "Udaipur,Tripura", value: "Udaipur,Tripura" },
  { label: "Achhnera,Uttar Pradesh", value: "Achhnera,Uttar Pradesh" },
  { label: "Adari,Uttar Pradesh", value: "Adari,Uttar Pradesh" },
  { label: "Agra,Uttar Pradesh", value: "Agra,Uttar Pradesh" },
  { label: "Aligarh,Uttar Pradesh", value: "Aligarh,Uttar Pradesh" },
  { label: "Allahabad,Uttar Pradesh", value: "Allahabad,Uttar Pradesh" },
  { label: "Amroha,Uttar Pradesh", value: "Amroha,Uttar Pradesh" },
  { label: "Azamgarh,Uttar Pradesh", value: "Azamgarh,Uttar Pradesh" },
  { label: "Bahraich,Uttar Pradesh", value: "Bahraich,Uttar Pradesh" },
  { label: "Ballia,Uttar Pradesh", value: "Ballia,Uttar Pradesh" },
  { label: "Balrampur,Uttar Pradesh", value: "Balrampur,Uttar Pradesh" },
  { label: "Banda,Uttar Pradesh", value: "Banda,Uttar Pradesh" },
  { label: "Bareilly,Uttar Pradesh", value: "Bareilly,Uttar Pradesh" },
  { label: "Chandausi,Uttar Pradesh", value: "Chandausi,Uttar Pradesh" },
  { label: "Dadri,Uttar Pradesh", value: "Dadri,Uttar Pradesh" },
  { label: "Deoria,Uttar Pradesh", value: "Deoria,Uttar Pradesh" },
  { label: "Etawah,Uttar Pradesh", value: "Etawah,Uttar Pradesh" },
  { label: "Fatehabad,Uttar Pradesh", value: "Fatehabad,Uttar Pradesh" },
  { label: "Fatehpur,Uttar Pradesh", value: "Fatehpur,Uttar Pradesh" },
  {
    label: "Greater Noida,Uttar Pradesh",
    value: "Greater Noida,Uttar Pradesh",
  },
  { label: "Hamirpur,Uttar Pradesh", value: "Hamirpur,Uttar Pradesh" },
  { label: "Hardoi,Uttar Pradesh", value: "Hardoi,Uttar Pradesh" },
  { label: "Jajmau,Uttar Pradesh", value: "Jajmau,Uttar Pradesh" },
  { label: "Jaunpur,Uttar Pradesh", value: "Jaunpur,Uttar Pradesh" },
  { label: "Jhansi,Uttar Pradesh", value: "Jhansi,Uttar Pradesh" },
  { label: "Kalpi,Uttar Pradesh", value: "Kalpi,Uttar Pradesh" },
  { label: "Kanpur,Uttar Pradesh", value: "Kanpur,Uttar Pradesh" },
  { label: "Kota,Uttar Pradesh", value: "Kota,Uttar Pradesh" },
  { label: "Laharpur,Uttar Pradesh", value: "Laharpur,Uttar Pradesh" },
  { label: "Lakhimpur,Uttar Pradesh", value: "Lakhimpur,Uttar Pradesh" },
  {
    label: "Lal Gopalganj Nindaura,Uttar Pradesh",
    value: "Lal Gopalganj Nindaura,Uttar Pradesh",
  },
  { label: "Lalganj,Uttar Pradesh", value: "Lalganj,Uttar Pradesh" },
  { label: "Lalitpur,Uttar Pradesh", value: "Lalitpur,Uttar Pradesh" },
  { label: "Lar,Uttar Pradesh", value: "Lar,Uttar Pradesh" },
  { label: "Loni,Uttar Pradesh", value: "Loni,Uttar Pradesh" },
  { label: "Lucknow,Uttar Pradesh", value: "Lucknow,Uttar Pradesh" },
  { label: "Mathura,Uttar Pradesh", value: "Mathura,Uttar Pradesh" },
  { label: "Meerut,Uttar Pradesh", value: "Meerut,Uttar Pradesh" },
  { label: "Modinagar,Uttar Pradesh", value: "Modinagar,Uttar Pradesh" },
  { label: "Muradnagar,Uttar Pradesh", value: "Muradnagar,Uttar Pradesh" },
  { label: "Nagina,Uttar Pradesh", value: "Nagina,Uttar Pradesh" },
  { label: "Najibabad,Uttar Pradesh", value: "Najibabad,Uttar Pradesh" },
  { label: "Nakur,Uttar Pradesh", value: "Nakur,Uttar Pradesh" },
  { label: "Nanpara,Uttar Pradesh", value: "Nanpara,Uttar Pradesh" },
  { label: "Naraura,Uttar Pradesh", value: "Naraura,Uttar Pradesh" },
  {
    label: "Naugawan Sadat,Uttar Pradesh",
    value: "Naugawan Sadat,Uttar Pradesh",
  },
  { label: "Nautanwa,Uttar Pradesh", value: "Nautanwa,Uttar Pradesh" },
  { label: "Nawabganj,Uttar Pradesh", value: "Nawabganj,Uttar Pradesh" },
  { label: "Nehtaur,Uttar Pradesh", value: "Nehtaur,Uttar Pradesh" },
  { label: "NOIDA,Uttar Pradesh", value: "NOIDA,Uttar Pradesh" },
  { label: "Noorpur,Uttar Pradesh", value: "Noorpur,Uttar Pradesh" },
  { label: "Obra,Uttar Pradesh", value: "Obra,Uttar Pradesh" },
  { label: "Orai,Uttar Pradesh", value: "Orai,Uttar Pradesh" },
  { label: "Padrauna,Uttar Pradesh", value: "Padrauna,Uttar Pradesh" },
  { label: "Palia Kalan,Uttar Pradesh", value: "Palia Kalan,Uttar Pradesh" },
  { label: "Parasi,Uttar Pradesh", value: "Parasi,Uttar Pradesh" },
  { label: "Phulpur,Uttar Pradesh", value: "Phulpur,Uttar Pradesh" },
  { label: "Pihani,Uttar Pradesh", value: "Pihani,Uttar Pradesh" },
  { label: "Pilibhit,Uttar Pradesh", value: "Pilibhit,Uttar Pradesh" },
  { label: "Pilkhuwa,Uttar Pradesh", value: "Pilkhuwa,Uttar Pradesh" },
  { label: "Powayan,Uttar Pradesh", value: "Powayan,Uttar Pradesh" },
  { label: "Pukhrayan,Uttar Pradesh", value: "Pukhrayan,Uttar Pradesh" },
  { label: "Puranpur,Uttar Pradesh", value: "Puranpur,Uttar Pradesh" },
  { label: "Purquazi,Uttar Pradesh", value: "Purquazi,Uttar Pradesh" },
  { label: "Purwa,Uttar Pradesh", value: "Purwa,Uttar Pradesh" },
  { label: "Rae Bareli,Uttar Pradesh", value: "Rae Bareli,Uttar Pradesh" },
  { label: "Rampur,Uttar Pradesh", value: "Rampur,Uttar Pradesh" },
  {
    label: "Rampur Maniharan,Uttar Pradesh",
    value: "Rampur Maniharan,Uttar Pradesh",
  },
  { label: "Rasra,Uttar Pradesh", value: "Rasra,Uttar Pradesh" },
  { label: "Rath,Uttar Pradesh", value: "Rath,Uttar Pradesh" },
  { label: "Renukoot,Uttar Pradesh", value: "Renukoot,Uttar Pradesh" },
  { label: "Reoti,Uttar Pradesh", value: "Reoti,Uttar Pradesh" },
  { label: "Robertsganj,Uttar Pradesh", value: "Robertsganj,Uttar Pradesh" },
  { label: "Rudauli,Uttar Pradesh", value: "Rudauli,Uttar Pradesh" },
  { label: "Rudrapur,Uttar Pradesh", value: "Rudrapur,Uttar Pradesh" },
  { label: "Sadabad,Uttar Pradesh", value: "Sadabad,Uttar Pradesh" },
  { label: "Safipur,Uttar Pradesh", value: "Safipur,Uttar Pradesh" },
  { label: "Saharanpur,Uttar Pradesh", value: "Saharanpur,Uttar Pradesh" },
  { label: "Sahaspur,Uttar Pradesh", value: "Sahaspur,Uttar Pradesh" },
  { label: "Sahaswan,Uttar Pradesh", value: "Sahaswan,Uttar Pradesh" },
  { label: "Sahawar,Uttar Pradesh", value: "Sahawar,Uttar Pradesh" },
  { label: "Sahjanwa,Uttar Pradesh", value: "Sahjanwa,Uttar Pradesh" },
  { label: "Saidpur, Ghazipur", value: "Saidpur, Ghazipur" },
  { label: "Sambhal,Uttar Pradesh", value: "Sambhal,Uttar Pradesh" },
  { label: "Samdhan,Uttar Pradesh", value: "Samdhan,Uttar Pradesh" },
  { label: "Samthar,Uttar Pradesh", value: "Samthar,Uttar Pradesh" },
  { label: "Sandi,Uttar Pradesh", value: "Sandi,Uttar Pradesh" },
  { label: "Sandila,Uttar Pradesh", value: "Sandila,Uttar Pradesh" },
  { label: "Sardhana,Uttar Pradesh", value: "Sardhana,Uttar Pradesh" },
  { label: "Seohara,Uttar Pradesh", value: "Seohara,Uttar Pradesh" },
  { label: "Shahabad, Hardoi", value: "Shahabad, Hardoi" },
  { label: "Shahabad, Rampur", value: "Shahabad, Rampur" },
  { label: "Shahganj,Uttar Pradesh", value: "Shahganj,Uttar Pradesh" },
  { label: "Shahjahanpur,Uttar Pradesh", value: "Shahjahanpur,Uttar Pradesh" },
  { label: "Shamli,Uttar Pradesh", value: "Shamli,Uttar Pradesh" },
  { label: "Shamsabad, Agra", value: "Shamsabad, Agra" },
  { label: "Shamsabad, Farrukhabad", value: "Shamsabad, Farrukhabad" },
  { label: "Sherkot,Uttar Pradesh", value: "Sherkot,Uttar Pradesh" },
  { label: "Shikarpur, Bulandshahr", value: "Shikarpur, Bulandshahr" },
  { label: "Shikohabad,Uttar Pradesh", value: "Shikohabad,Uttar Pradesh" },
  { label: "Shishgarh,Uttar Pradesh", value: "Shishgarh,Uttar Pradesh" },
  { label: "Siana,Uttar Pradesh", value: "Siana,Uttar Pradesh" },
  { label: "Sikanderpur,Uttar Pradesh", value: "Sikanderpur,Uttar Pradesh" },
  { label: "Sikandra Rao,Uttar Pradesh", value: "Sikandra Rao,Uttar Pradesh" },
  { label: "Sikandrabad,Uttar Pradesh", value: "Sikandrabad,Uttar Pradesh" },
  { label: "Sirsaganj,Uttar Pradesh", value: "Sirsaganj,Uttar Pradesh" },
  { label: "Sirsi,Uttar Pradesh", value: "Sirsi,Uttar Pradesh" },
  { label: "Sitapur,Uttar Pradesh", value: "Sitapur,Uttar Pradesh" },
  { label: "Soron,Uttar Pradesh", value: "Soron,Uttar Pradesh" },
  { label: "Suar,Uttar Pradesh", value: "Suar,Uttar Pradesh" },
  { label: "Sultanpur,Uttar Pradesh", value: "Sultanpur,Uttar Pradesh" },
  { label: "Sumerpur,Uttar Pradesh", value: "Sumerpur,Uttar Pradesh" },
  { label: "Tanda,Uttar Pradesh", value: "Tanda,Uttar Pradesh" },
  { label: "Tetri Bazar,Uttar Pradesh", value: "Tetri Bazar,Uttar Pradesh" },
  { label: "Thakurdwara,Uttar Pradesh", value: "Thakurdwara,Uttar Pradesh" },
  { label: "Thana Bhawan,Uttar Pradesh", value: "Thana Bhawan,Uttar Pradesh" },
  { label: "Tilhar,Uttar Pradesh", value: "Tilhar,Uttar Pradesh" },
  { label: "Tirwaganj,Uttar Pradesh", value: "Tirwaganj,Uttar Pradesh" },
  { label: "Tulsipur,Uttar Pradesh", value: "Tulsipur,Uttar Pradesh" },
  { label: "Tundla,Uttar Pradesh", value: "Tundla,Uttar Pradesh" },
  { label: "Unnao,Uttar Pradesh", value: "Unnao,Uttar Pradesh" },
  { label: "Utraula,Uttar Pradesh", value: "Utraula,Uttar Pradesh" },
  { label: "Varanasi,Uttar Pradesh", value: "Varanasi,Uttar Pradesh" },
  { label: "Vrindavan,Uttar Pradesh", value: "Vrindavan,Uttar Pradesh" },
  { label: "Warhapur,Uttar Pradesh", value: "Warhapur,Uttar Pradesh" },
  { label: "Zaidpur,Uttar Pradesh", value: "Zaidpur,Uttar Pradesh" },
  { label: "Zamania,Uttar Pradesh", value: "Zamania,Uttar Pradesh" },
  { label: "Almora,Uttarakhand", value: "Almora,Uttarakhand" },
  { label: "Bazpur,Uttarakhand", value: "Bazpur,Uttarakhand" },
  { label: "Chamba,Uttarakhand", value: "Chamba,Uttarakhand" },
  { label: "Dehradun,Uttarakhand", value: "Dehradun,Uttarakhand" },
  { label: "Haldwani,Uttarakhand", value: "Haldwani,Uttarakhand" },
  { label: "Haridwar,Uttarakhand", value: "Haridwar,Uttarakhand" },
  { label: "Jaspur,Uttarakhand", value: "Jaspur,Uttarakhand" },
  { label: "Kashipur,Uttarakhand", value: "Kashipur,Uttarakhand" },
  { label: "kichha,Uttarakhand", value: "kichha,Uttarakhand" },
  { label: "Kotdwara,Uttarakhand", value: "Kotdwara,Uttarakhand" },
  { label: "Manglaur,Uttarakhand", value: "Manglaur,Uttarakhand" },
  { label: "Mussoorie,Uttarakhand", value: "Mussoorie,Uttarakhand" },
  { label: "Nagla,Uttarakhand", value: "Nagla,Uttarakhand" },
  { label: "Nainital,Uttarakhand", value: "Nainital,Uttarakhand" },
  { label: "Pauri,Uttarakhand", value: "Pauri,Uttarakhand" },
  { label: "Pithoragarh,Uttarakhand", value: "Pithoragarh,Uttarakhand" },
  { label: "Ramnagar,Uttarakhand", value: "Ramnagar,Uttarakhand" },
  { label: "Rishikesh,Uttarakhand", value: "Rishikesh,Uttarakhand" },
  { label: "Roorkee,Uttarakhand", value: "Roorkee,Uttarakhand" },
  { label: "Rudrapur,Uttarakhand", value: "Rudrapur,Uttarakhand" },
  { label: "Sitarganj,Uttarakhand", value: "Sitarganj,Uttarakhand" },
  { label: "Tehri,Uttarakhand", value: "Tehri,Uttarakhand" },
  {
    label: "Muzaffarnagar,Uttar Pradesh",
    value: "Muzaffarnagar,Uttar Pradesh",
  },
  { label: "Adra, Purulia", value: "Adra, Purulia" },
  { label: "Alipurduar,West Bengal", value: "Alipurduar,West Bengal" },
  { label: "Arambagh,West Bengal", value: "Arambagh,West Bengal" },
  { label: "Asansol,West Bengal", value: "Asansol,West Bengal" },
  { label: "Baharampur,West Bengal", value: "Baharampur,West Bengal" },
  { label: "Bally,West Bengal", value: "Bally,West Bengal" },
  { label: "Balurghat,West Bengal", value: "Balurghat,West Bengal" },
  { label: "Bankura,West Bengal", value: "Bankura,West Bengal" },
  { label: "Barakar,West Bengal", value: "Barakar,West Bengal" },
  { label: "Barasat,West Bengal", value: "Barasat,West Bengal" },
  { label: "Bardhaman,West Bengal", value: "Bardhaman,West Bengal" },
  { label: "Bidhan Nagar,West Bengal", value: "Bidhan Nagar,West Bengal" },
  { label: "Chinsura,West Bengal", value: "Chinsura,West Bengal" },
  { label: "Contai,West Bengal", value: "Contai,West Bengal" },
  { label: "Cooch Behar,West Bengal", value: "Cooch Behar,West Bengal" },
  { label: "Darjeeling,West Bengal", value: "Darjeeling,West Bengal" },
  { label: "Durgapur,West Bengal", value: "Durgapur,West Bengal" },
  { label: "Haldia,West Bengal", value: "Haldia,West Bengal" },
  { label: "Howrah,West Bengal", value: "Howrah,West Bengal" },
  { label: "Islampur,West Bengal", value: "Islampur,West Bengal" },
  { label: "Jhargram,West Bengal", value: "Jhargram,West Bengal" },
  { label: "Kharagpur,West Bengal", value: "Kharagpur,West Bengal" },
  { label: "Kolkata,West Bengal", value: "Kolkata,West Bengal" },
  { label: "Mainaguri,West Bengal", value: "Mainaguri,West Bengal" },
  { label: "Mal,West Bengal", value: "Mal,West Bengal" },
  { label: "Mathabhanga,West Bengal", value: "Mathabhanga,West Bengal" },
  { label: "Medinipur,West Bengal", value: "Medinipur,West Bengal" },
  { label: "Memari,West Bengal", value: "Memari,West Bengal" },
  { label: "Monoharpur,West Bengal", value: "Monoharpur,West Bengal" },
  { label: "Murshidabad,West Bengal", value: "Murshidabad,West Bengal" },
  { label: "Nabadwip,West Bengal", value: "Nabadwip,West Bengal" },
  { label: "Naihati,West Bengal", value: "Naihati,West Bengal" },
  { label: "Panchla,West Bengal", value: "Panchla,West Bengal" },
  { label: "Pandua,West Bengal", value: "Pandua,West Bengal" },
  {
    label: "Paschim Punropara,West Bengal",
    value: "Paschim Punropara,West Bengal",
  },
  { label: "Purulia,West Bengal", value: "Purulia,West Bengal" },
  { label: "Raghunathpur,West Bengal", value: "Raghunathpur,West Bengal" },
  { label: "Raiganj,West Bengal", value: "Raiganj,West Bengal" },
  { label: "Rampurhat,West Bengal", value: "Rampurhat,West Bengal" },
  { label: "Ranaghat,West Bengal", value: "Ranaghat,West Bengal" },
  { label: "Sainthia,West Bengal", value: "Sainthia,West Bengal" },
  { label: "Santipur,West Bengal", value: "Santipur,West Bengal" },
  { label: "Siliguri,West Bengal", value: "Siliguri,West Bengal" },
  { label: "Sonamukhi,West Bengal", value: "Sonamukhi,West Bengal" },
  { label: "Srirampore,West Bengal", value: "Srirampore,West Bengal" },
  { label: "Suri,West Bengal", value: "Suri,West Bengal" },
  { label: "Taki,West Bengal", value: "Taki,West Bengal" },
  { label: "Tamluk,West Bengal", value: "Tamluk,West Bengal" },
  { label: "Tarakeswar,West Bengal", value: "Tarakeswar,West Bengal" },
  { label: "Chikmagalur,Karnataka", value: "Chikmagalur,Karnataka" },
  { label: "Davanagere,Karnataka", value: "Davanagere,Karnataka" },
  { label: "Dharwad,Karnataka", value: "Dharwad,Karnataka" },
  { label: "Gadag,Karnataka", value: "Gadag,Karnataka" },
];


